const WORDS = [
  // Animals
  { id:1, word:"cat", phonetic:"/kæt/", thai:"แมว", category:"animals", level:"A1", rhyme:"แมว นอน เหนือ เบาะ นุ่ม นาน", example:"The cat is sleeping.", exampleThai:"แมวกำลังนอนหลับ", rhymeGroup:"at" },
  { id:2, word:"dog", phonetic:"/dɒɡ/", thai:"สุนัข", category:"animals", level:"A1", rhyme:"หมา หาง ยาว เคี้ยว กระดูก", example:"My dog is friendly.", exampleThai:"สุนัขของฉันเป็นมิตร", rhymeGroup:"og" },
  { id:3, word:"bird", phonetic:"/bɜːd/", thai:"นก", category:"animals", level:"A1", rhyme:"นก บิน สูง แสน สวย ไกล", example:"The bird sings in the tree.", exampleThai:"นกร้องเพลงบนต้นไม้", rhymeGroup:"ird" },
  { id:4, word:"fish", phonetic:"/fɪʃ/", thai:"ปลา", category:"animals", level:"A1", rhyme:"ปลา ว่าย น้ำ ใส แสน สดชื่น", example:"Fish live in water.", exampleThai:"ปลาอาศัยอยู่ในน้ำ", rhymeGroup:"ish" },
  { id:5, word:"cow", phonetic:"/kaʊ/", thai:"วัว", category:"animals", level:"A1", rhyme:"วัว กิน หญ้า ทุ่ง เขียว ตลอด", example:"The cow eats grass.", exampleThai:"วัวกินหญ้า", rhymeGroup:"ow" },
  { id:6, word:"horse", phonetic:"/hɔːs/", thai:"ม้า", category:"animals", level:"A1", rhyme:"ม้า วิ่ง เร็ว ดั่ง ลม แรง", example:"The horse runs fast.", exampleThai:"ม้าวิ่งเร็ว", rhymeGroup:"orse" },
  { id:7, word:"sheep", phonetic:"/ʃiːp/", thai:"แกะ", category:"animals", level:"A1", rhyme:"แกะ ขนฟู นุ่ม นวล เหมือน เมฆ", example:"The sheep has white wool.", exampleThai:"แกะมีขนสีขาว", rhymeGroup:"eep" },
  { id:8, word:"pig", phonetic:"/pɪɡ/", thai:"หมู", category:"animals", level:"A1", rhyme:"หมู อ้วน กลม กินเก่ง แสน ซน", example:"The pig rolls in mud.", exampleThai:"หมูชอบนอนในโคลน", rhymeGroup:"ig" },
  { id:9, word:"elephant", phonetic:"/ˈelɪfənt/", thai:"ช้าง", category:"animals", level:"A1", rhyme:"ช้าง ใหญ่ โต งวง ยาว แสน น่า รัก", example:"An elephant never forgets.", exampleThai:"ช้างไม่เคยลืม", rhymeGroup:"ant" },
  { id:10, word:"monkey", phonetic:"/ˈmʌŋki/", thai:"ลิง", category:"animals", level:"A1", rhyme:"ลิง ห้อย โหน เด้ง เต้น สนุก", example:"The monkey climbs trees.", exampleThai:"ลิงปีนต้นไม้", rhymeGroup:"ey" },

  // Colors
  { id:11, word:"red", phonetic:"/red/", thai:"สีแดง", category:"colors", level:"A1", rhyme:"แดง ดั่ง ดอกกุหลาบ งาม จริง", example:"The apple is red.", exampleThai:"แอปเปิ้ลสีแดง", rhymeGroup:"ed" },
  { id:12, word:"blue", phonetic:"/bluː/", thai:"สีน้ำเงิน", category:"colors", level:"A1", rhyme:"น้ำเงิน ท้องฟ้า กว้าง ใหญ่ สดใส", example:"The sky is blue.", exampleThai:"ท้องฟ้าสีน้ำเงิน", rhymeGroup:"ue" },
  { id:13, word:"green", phonetic:"/ɡriːn/", thai:"สีเขียว", category:"colors", level:"A1", rhyme:"เขียว ใบไม้ สด ชุ่ม ชื่น ตา", example:"Leaves are green.", exampleThai:"ใบไม้สีเขียว", rhymeGroup:"een" },
  { id:14, word:"yellow", phonetic:"/ˈjeloʊ/", thai:"สีเหลือง", category:"colors", level:"A1", rhyme:"เหลือง ดั่ง แสง ทอง ส่อง สว่าง", example:"The sun is yellow.", exampleThai:"ดวงอาทิตย์สีเหลือง", rhymeGroup:"ow" },
  { id:15, word:"white", phonetic:"/waɪt/", thai:"สีขาว", category:"colors", level:"A1", rhyme:"ขาว ดั่ง หิมะ บริสุทธิ์ ดี งาม", example:"Snow is white.", exampleThai:"หิมะสีขาว", rhymeGroup:"ite" },
  { id:16, word:"black", phonetic:"/blæk/", thai:"สีดำ", category:"colors", level:"A1", rhyme:"ดำ ดั่ง คืน มืด มิด สนิท", example:"The night is black.", exampleThai:"ราตรีมืดดำ", rhymeGroup:"ack" },
  { id:17, word:"orange", phonetic:"/ˈɒrɪndʒ/", thai:"สีส้ม", category:"colors", level:"A1", rhyme:"ส้ม สีสด ชวน ชม แสน งาม", example:"Oranges are orange!", exampleThai:"ส้มสีส้ม!", rhymeGroup:"ange" },
  { id:18, word:"pink", phonetic:"/pɪŋk/", thai:"สีชมพู", category:"colors", level:"A1", rhyme:"ชมพู สดใส หัวใจ เต้น แรง", example:"Her dress is pink.", exampleThai:"ชุดของเธอสีชมพู", rhymeGroup:"ink" },

  // Food
  { id:19, word:"apple", phonetic:"/ˈæpəl/", thai:"แอปเปิ้ล", category:"food", level:"A1", rhyme:"แอปเปิ้ล กรุบ กรอบ หวาน อมฤต", example:"An apple a day is healthy.", exampleThai:"กินแอปเปิ้ลทุกวันดีต่อสุขภาพ", rhymeGroup:"le" },
  { id:20, word:"banana", phonetic:"/bəˈnɑːnə/", thai:"กล้วย", category:"food", level:"A1", rhyme:"กล้วย หวาน นุ่ม ลิ้น ลิงชอบ กิน", example:"Monkeys love bananas.", exampleThai:"ลิงชอบกล้วย", rhymeGroup:"ana" },
  { id:21, word:"bread", phonetic:"/bred/", thai:"ขนมปัง", category:"food", level:"A1", rhyme:"ขนมปัง อบ ใหม่ กลิ่น หอม ชวน กิน", example:"I eat bread for breakfast.", exampleThai:"ฉันกินขนมปังตอนเช้า", rhymeGroup:"ead" },
  { id:22, word:"rice", phonetic:"/raɪs/", thai:"ข้าว", category:"food", level:"A1", rhyme:"ข้าว ร้อน ฉ่ำ หอม อิ่ม ท้อง", example:"We eat rice every day.", exampleThai:"เรากินข้าวทุกวัน", rhymeGroup:"ice" },
  { id:23, word:"milk", phonetic:"/mɪlk/", thai:"นม", category:"food", level:"A1", rhyme:"นม ขาว ขุ่น หวาน มัน แสน อร่อย", example:"Children drink milk.", exampleThai:"เด็กๆ ดื่มนม", rhymeGroup:"ilk" },
  { id:24, word:"water", phonetic:"/ˈwɔːtər/", thai:"น้ำ", category:"food", level:"A1", rhyme:"น้ำ ใส สะอาด ดื่ม ชื่น ชุ่ม คอ", example:"Water is life.", exampleThai:"น้ำคือชีวิต", rhymeGroup:"ater" },
  { id:25, word:"egg", phonetic:"/eɡ/", thai:"ไข่", category:"food", level:"A1", rhyme:"ไข่ กลม มน แดง ใน ขาว นอก", example:"I eat an egg every morning.", exampleThai:"ฉันกินไข่ทุกเช้า", rhymeGroup:"eg" },
  { id:26, word:"cake", phonetic:"/keɪk/", thai:"เค้ก", category:"food", level:"A1", rhyme:"เค้ก หวาน นุ่ม ฟู สุขสันต์ วันเกิด", example:"Happy birthday cake!", exampleThai:"เค้กวันเกิดแสนหวาน", rhymeGroup:"ake" },
  { id:27, word:"soup", phonetic:"/suːp/", thai:"ซุป", category:"food", level:"A1", rhyme:"ซุป ร้อน อุ่น กลิ่น หอม อาหาร", example:"Hot soup warms you up.", exampleThai:"ซุปร้อนทำให้อบอุ่น", rhymeGroup:"oup" },
  { id:28, word:"orange", phonetic:"/ˈɒrɪndʒ/", thai:"ส้ม", category:"food", level:"A1", rhyme:"ส้ม เปรี้ยว หวาน วิตามิน ซี สด", example:"Oranges are full of vitamin C.", exampleThai:"ส้มมีวิตามินซีมาก", rhymeGroup:"ange" },

  // School/Learning
  { id:29, word:"book", phonetic:"/bʊk/", thai:"หนังสือ", category:"school", level:"A1", rhyme:"หนังสือ เปิด อ่าน ฝัน ถึง โลก กว้าง", example:"I love reading books.", exampleThai:"ฉันชอบอ่านหนังสือ", rhymeGroup:"ook" },
  { id:30, word:"pen", phonetic:"/pen/", thai:"ปากกา", category:"school", level:"A1", rhyme:"ปากกา เขียน ฝัน ลงกระดาษ", example:"Write with a pen.", exampleThai:"เขียนด้วยปากกา", rhymeGroup:"en" },
  { id:31, word:"school", phonetic:"/skuːl/", thai:"โรงเรียน", category:"school", level:"A1", rhyme:"โรงเรียน เรียน รู้ สนุก สดใส ทุกวัน", example:"I go to school every day.", exampleThai:"ฉันไปโรงเรียนทุกวัน", rhymeGroup:"ool" },
  { id:32, word:"teacher", phonetic:"/ˈtiːtʃər/", thai:"ครู", category:"school", level:"A1", rhyme:"ครู สอน ดี มีน้ำใจ แสน ดี งาม", example:"My teacher is kind.", exampleThai:"ครูของฉันใจดี", rhymeGroup:"er" },
  { id:33, word:"student", phonetic:"/ˈstjuːdənt/", thai:"นักเรียน", category:"school", level:"A1", rhyme:"นักเรียน ขยัน เรียน เก่ง ฝัน ไกล", example:"The student studies hard.", exampleThai:"นักเรียนเรียนหนัก", rhymeGroup:"ent" },
  { id:34, word:"class", phonetic:"/klɑːs/", thai:"ชั้นเรียน", category:"school", level:"A1", rhyme:"ห้องเรียน สดใส ใฝ่ รู้ ดี งาม", example:"Our class is fun.", exampleThai:"ชั้นเรียนของเราสนุก", rhymeGroup:"ass" },
  { id:35, word:"number", phonetic:"/ˈnʌmbər/", thai:"ตัวเลข", category:"school", level:"A1", rhyme:"ตัวเลข นับ สนุก หนึ่ง สอง สาม", example:"Can you count numbers?", exampleThai:"คุณนับเลขได้ไหม", rhymeGroup:"er" },
  { id:36, word:"letter", phonetic:"/ˈletər/", thai:"ตัวอักษร", category:"school", level:"A1", rhyme:"ตัวอักษร เรียง ราย A B C", example:"The alphabet has 26 letters.", exampleThai:"ตัวอักษรมี 26 ตัว", rhymeGroup:"etter" },
  { id:37, word:"read", phonetic:"/riːd/", thai:"อ่าน", category:"school", level:"A1", rhyme:"อ่าน หนังสือ เรื่อย ๆ รู้ มาก ขึ้น", example:"Read a book today!", exampleThai:"อ่านหนังสือวันนี้เลย!", rhymeGroup:"ead" },
  { id:38, word:"write", phonetic:"/raɪt/", thai:"เขียน", category:"school", level:"A1", rhyme:"เขียน ความ ฝัน ลงกระดาษ สีขาว", example:"Write your name here.", exampleThai:"เขียนชื่อของคุณตรงนี้", rhymeGroup:"ite" },
  { id:39, word:"learn", phonetic:"/lɜːn/", thai:"เรียนรู้", category:"school", level:"A1", rhyme:"เรียน รู้ ทุก วัน สนุก ไม่มี ที่สิ้น สุด", example:"Never stop learning!", exampleThai:"อย่าหยุดเรียนรู้!", rhymeGroup:"earn" },
  { id:40, word:"answer", phonetic:"/ˈɑːnsər/", thai:"คำตอบ", category:"school", level:"A1", rhyme:"คำตอบ ตั้ง ใจ คิด ดี ๆ จะ พบ", example:"Do you know the answer?", exampleThai:"คุณรู้คำตอบไหม?", rhymeGroup:"er" },

  // Body
  { id:41, word:"hand", phonetic:"/hænd/", thai:"มือ", category:"body", level:"A1", rhyme:"มือ สร้าง สรรค์ งาน ดี ด้วย หัวใจ", example:"Wash your hands!", exampleThai:"ล้างมือด้วยนะ!", rhymeGroup:"and" },
  { id:42, word:"eye", phonetic:"/aɪ/", thai:"ตา", category:"body", level:"A1", rhyme:"ตา มอง โลก สวย งาม สดใส", example:"Open your eyes!", exampleThai:"ลืมตาขึ้น!", rhymeGroup:"eye" },
  { id:43, word:"ear", phonetic:"/ɪər/", thai:"หู", category:"body", level:"A1", rhyme:"หู ฟัง เสียง เพลง หวาน ชื่น ใจ", example:"Listen with your ears.", exampleThai:"ฟังด้วยหู", rhymeGroup:"ear" },
  { id:44, word:"mouth", phonetic:"/maʊθ/", thai:"ปาก", category:"body", level:"A1", rhyme:"ปาก พูด ดี มี มนต์ เสน่ห์ งาม", example:"Smile with your mouth.", exampleThai:"ยิ้มด้วยปาก", rhymeGroup:"outh" },
  { id:45, word:"nose", phonetic:"/noʊz/", thai:"จมูก", category:"body", level:"A1", rhyme:"จมูก ดม กลิ่น หอม อาหาร แสน อยาก", example:"Your nose smells.", exampleThai:"จมูกใช้ดมกลิ่น", rhymeGroup:"ose" },
  { id:46, word:"head", phonetic:"/hed/", thai:"หัว", category:"body", level:"A1", rhyme:"หัว คิด ดี ฝัน ไกล ถึง ดาว", example:"Use your head to think.", exampleThai:"ใช้หัวคิด", rhymeGroup:"ead" },
  { id:47, word:"foot", phonetic:"/fʊt/", thai:"เท้า", category:"body", level:"A1", rhyme:"เท้า ก้าว เดิน ไกล ถึง จุด หมาย", example:"Put your best foot forward.", exampleThai:"ก้าวเดินไปข้างหน้า", rhymeGroup:"oot" },
  { id:48, word:"heart", phonetic:"/hɑːt/", thai:"หัวใจ", category:"body", level:"A1", rhyme:"หัวใจ เต้น แรง รัก จริง ไม่มี วัน ดับ", example:"The heart pumps blood.", exampleThai:"หัวใจสูบฉีดเลือด", rhymeGroup:"art" },

  // Nature
  { id:49, word:"sun", phonetic:"/sʌn/", thai:"ดวงอาทิตย์", category:"nature", level:"A1", rhyme:"ดวงอาทิตย์ ส่อง แสง ทอง ส่อง ไกล", example:"The sun rises in the east.", exampleThai:"ดวงอาทิตย์ขึ้นทางทิศตะวันออก", rhymeGroup:"un" },
  { id:50, word:"moon", phonetic:"/muːn/", thai:"ดวงจันทร์", category:"nature", level:"A1", rhyme:"จันทร์ แจ่ม ฟ้า ยาม ค่ำ คืน งาม", example:"The moon shines at night.", exampleThai:"ดวงจันทร์ส่องแสงตอนกลางคืน", rhymeGroup:"oon" },
  { id:51, word:"star", phonetic:"/stɑːr/", thai:"ดาว", category:"nature", level:"A1", rhyme:"ดาว ระยิบ ระยับ สวย บน ฟ้า กว้าง", example:"Stars shine in the sky.", exampleThai:"ดาวส่องแสงบนท้องฟ้า", rhymeGroup:"ar" },
  { id:52, word:"tree", phonetic:"/triː/", thai:"ต้นไม้", category:"nature", level:"A1", rhyme:"ต้นไม้ ใหญ่ โต ร่ม เย็น แสน ดี", example:"Trees give us fresh air.", exampleThai:"ต้นไม้ให้อากาศบริสุทธิ์", rhymeGroup:"ee" },
  { id:53, word:"flower", phonetic:"/ˈflaʊər/", thai:"ดอกไม้", category:"nature", level:"A1", rhyme:"ดอกไม้ บาน สวย งาม กลิ่น หอม ไกล", example:"Flowers smell beautiful.", exampleThai:"ดอกไม้มีกลิ่นหอม", rhymeGroup:"er" },
  { id:54, word:"rain", phonetic:"/reɪn/", thai:"ฝน", category:"nature", level:"A1", rhyme:"ฝน ตก ชุ่ม ชื่น ดิน แผ่น ดิน ดี", example:"The rain waters the plants.", exampleThai:"ฝนรดน้ำต้นไม้", rhymeGroup:"ain" },
  { id:55, word:"wind", phonetic:"/wɪnd/", thai:"ลม", category:"nature", level:"A1", rhyme:"ลม พัด เย็น ชื่น ใจ สดชื่น", example:"The wind blows cool.", exampleThai:"ลมพัดเย็นสบาย", rhymeGroup:"ind" },
  { id:56, word:"cloud", phonetic:"/klaʊd/", thai:"เมฆ", category:"nature", level:"A1", rhyme:"เมฆ ลอย สูง ฟ้า ขาว ฟู ดั่ง ฝ้าย", example:"White clouds float by.", exampleThai:"เมฆขาวลอยผ่าน", rhymeGroup:"oud" },
  { id:57, word:"river", phonetic:"/ˈrɪvər/", thai:"แม่น้ำ", category:"nature", level:"A1", rhyme:"แม่น้ำ ไหล เอื่อย ๆ มา จาก ภูเขา สูง", example:"Fish swim in the river.", exampleThai:"ปลาว่ายในแม่น้ำ", rhymeGroup:"er" },
  { id:58, word:"mountain", phonetic:"/ˈmaʊntɪn/", thai:"ภูเขา", category:"nature", level:"A1", rhyme:"ภูเขา สูง ตระหง่าน ยืน หยัด มั่น คง", example:"Mountains are very tall.", exampleThai:"ภูเขาสูงมาก", rhymeGroup:"ain" },
  { id:59, word:"sea", phonetic:"/siː/", thai:"ทะเล", category:"nature", level:"A1", rhyme:"ทะเล กว้าง ใหญ่ คลื่น ซัด ฝั่ง ไกล", example:"The sea is deep and blue.", exampleThai:"ทะเลลึกและสีน้ำเงิน", rhymeGroup:"ee" },
  { id:60, word:"sky", phonetic:"/skaɪ/", thai:"ท้องฟ้า", category:"nature", level:"A1", rhyme:"ฟ้า กว้าง ไกล สุด ตา แสน สวย งาม", example:"The sky is blue today.", exampleThai:"ท้องฟ้าวันนี้สีฟ้า", rhymeGroup:"y" },

  // Family
  { id:61, word:"mother", phonetic:"/ˈmʌðər/", thai:"แม่", category:"family", level:"A1", rhyme:"แม่ รัก ลูก สุด ใจ จริง ไม่ เคย เปลี่ยน", example:"My mother loves me.", exampleThai:"แม่รักฉัน", rhymeGroup:"er" },
  { id:62, word:"father", phonetic:"/ˈfɑːðər/", thai:"พ่อ", category:"family", level:"A1", rhyme:"พ่อ แข็งแกร่ง ดั่ง ต้นไม้ ใหญ่ โต", example:"My father works hard.", exampleThai:"พ่อทำงานหนัก", rhymeGroup:"er" },
  { id:63, word:"brother", phonetic:"/ˈbrʌðər/", thai:"พี่ชาย/น้องชาย", category:"family", level:"A1", rhyme:"พี่ น้อง รัก กัน ไม่ ลืม ตลอด ไป", example:"My brother is funny.", exampleThai:"พี่ชายของฉันตลก", rhymeGroup:"er" },
  { id:64, word:"sister", phonetic:"/ˈsɪstər/", thai:"พี่สาว/น้องสาว", category:"family", level:"A1", rhyme:"พี่สาว หวาน ใจ ดี น้ำใจ งาม", example:"My sister is kind.", exampleThai:"น้องสาวของฉันใจดี", rhymeGroup:"er" },
  { id:65, word:"baby", phonetic:"/ˈbeɪbi/", thai:"ทารก", category:"family", level:"A1", rhyme:"ทารก น้อย เล็ก น่า รัก หัวใจ ละลาย", example:"The baby is sleeping.", exampleThai:"ทารกกำลังนอนหลับ", rhymeGroup:"y" },
  { id:66, word:"friend", phonetic:"/frend/", thai:"เพื่อน", category:"family", level:"A1", rhyme:"เพื่อน ดี คู่ ใจ ไม่ เคย ทิ้ง กัน", example:"Friends help each other.", exampleThai:"เพื่อนช่วยเหลือกัน", rhymeGroup:"end" },

  // Home
  { id:67, word:"house", phonetic:"/haʊs/", thai:"บ้าน", category:"home", level:"A1", rhyme:"บ้าน อบอุ่น ครอบครัว พัก ผ่อน ร่มเย็น", example:"My house is small but cozy.", exampleThai:"บ้านฉันเล็กแต่อบอุ่น", rhymeGroup:"ouse" },
  { id:68, word:"door", phonetic:"/dɔːr/", thai:"ประตู", category:"home", level:"A1", rhyme:"ประตู เปิด รับ แขก ยิ้ม รับ ทุก คน", example:"Please open the door.", exampleThai:"กรุณาเปิดประตู", rhymeGroup:"oor" },
  { id:69, word:"window", phonetic:"/ˈwɪndoʊ/", thai:"หน้าต่าง", category:"home", level:"A1", rhyme:"หน้าต่าง เปิด รับ ลม เย็น ชื่น ใจ", example:"Look out the window!", exampleThai:"มองออกไปนอกหน้าต่าง!", rhymeGroup:"ow" },
  { id:70, word:"bed", phonetic:"/bed/", thai:"เตียง", category:"home", level:"A1", rhyme:"เตียง นุ่ม นวล นอน หลับ ฝัน ดี", example:"Time to go to bed.", exampleThai:"ถึงเวลานอนแล้ว", rhymeGroup:"ed" },
  { id:71, word:"chair", phonetic:"/tʃeər/", thai:"เก้าอี้", category:"home", level:"A1", rhyme:"เก้าอี้ นั่ง พัก ผ่อน สบาย ดี", example:"Sit on the chair.", exampleThai:"นั่งบนเก้าอี้", rhymeGroup:"air" },
  { id:72, word:"table", phonetic:"/ˈteɪbəl/", thai:"โต๊ะ", category:"home", level:"A1", rhyme:"โต๊ะ วาง อาหาร ร่วม รับ ประทาน กัน", example:"Eat at the table.", exampleThai:"กินอาหารที่โต๊ะ", rhymeGroup:"able" },
  { id:73, word:"kitchen", phonetic:"/ˈkɪtʃɪn/", thai:"ห้องครัว", category:"home", level:"A1", rhyme:"ครัว กลิ่น หอม อาหาร สุก กำลัง รอ", example:"Cooking happens in the kitchen.", exampleThai:"ทำอาหารในห้องครัว", rhymeGroup:"en" },
  { id:74, word:"garden", phonetic:"/ˈɡɑːrdən/", thai:"สวน", category:"home", level:"A1", rhyme:"สวน ดอกไม้ บาน สวย งาม ต้อง ตา", example:"I water my garden every day.", exampleThai:"ฉันรดน้ำสวนทุกวัน", rhymeGroup:"en" },

  // Transport
  { id:75, word:"car", phonetic:"/kɑːr/", thai:"รถยนต์", category:"transport", level:"A1", rhyme:"รถ วิ่ง ไว ตาม ถนน ไกล สุด ลับ ตา", example:"The car goes fast.", exampleThai:"รถยนต์วิ่งเร็ว", rhymeGroup:"ar" },
  { id:76, word:"bus", phonetic:"/bʌs/", thai:"รถบัส", category:"transport", level:"A1", rhyme:"รถ บัส พา ผู้ โดยสาร ไป ถึง ที่ หมาย", example:"Take the bus to school.", exampleThai:"นั่งรถบัสไปโรงเรียน", rhymeGroup:"us" },
  { id:77, word:"train", phonetic:"/treɪn/", thai:"รถไฟ", category:"transport", level:"A1", rhyme:"รถ ไฟ วิ่ง ราง เรียง ราย ไป ข้างหน้า", example:"The train is on time.", exampleThai:"รถไฟตรงเวลา", rhymeGroup:"ain" },
  { id:78, word:"plane", phonetic:"/pleɪn/", thai:"เครื่องบิน", category:"transport", level:"A1", rhyme:"บิน สูง ลิบ เมฆ สีขาว ล้อมรอบ", example:"The plane flies high.", exampleThai:"เครื่องบินบินสูง", rhymeGroup:"ane" },
  { id:79, word:"boat", phonetic:"/boʊt/", thai:"เรือ", category:"transport", level:"A1", rhyme:"เรือ ลอย น้ำ ลม พัด เบา ๆ ชื่น ใจ", example:"The boat sails on the sea.", exampleThai:"เรือแล่นในทะเล", rhymeGroup:"oat" },
  { id:80, word:"bicycle", phonetic:"/ˈbaɪsɪkəl/", thai:"จักรยาน", category:"transport", level:"A1", rhyme:"จักรยาน ปั่น เพลิน ใจ ลม เย็น ชื่น", example:"Ride your bicycle to school.", exampleThai:"ขี่จักรยานไปโรงเรียน", rhymeGroup:"le" },

  // Actions / Verbs A2
  { id:81, word:"run", phonetic:"/rʌn/", thai:"วิ่ง", category:"actions", level:"A1", rhyme:"วิ่ง เร็ว แรง สุด ใจ ไม่ หยุด", example:"I run every morning.", exampleThai:"ฉันวิ่งทุกเช้า", rhymeGroup:"un" },
  { id:82, word:"jump", phonetic:"/dʒʌmp/", thai:"กระโดด", category:"actions", level:"A1", rhyme:"กระโดด สูง ไกล ใจ กล้า ไม่ กลัว", example:"Jump as high as you can!", exampleThai:"กระโดดให้สูงที่สุดเท่าที่ทำได้!", rhymeGroup:"ump" },
  { id:83, word:"swim", phonetic:"/swɪm/", thai:"ว่ายน้ำ", category:"actions", level:"A1", rhyme:"ว่าย น้ำ เย็น ชื่น สดชื่น เหมือน ปลา", example:"Fish swim in the ocean.", exampleThai:"ปลาว่ายน้ำในมหาสมุทร", rhymeGroup:"im" },
  { id:84, word:"sing", phonetic:"/sɪŋ/", thai:"ร้องเพลง", category:"actions", level:"A1", rhyme:"ร้อง เพลง หวาน ชื่น ใจ ทุก คน ยิ้ม", example:"Sing a happy song!", exampleThai:"ร้องเพลงสนุก!", rhymeGroup:"ing" },
  { id:85, word:"dance", phonetic:"/dɑːns/", thai:"เต้น", category:"actions", level:"A1", rhyme:"เต้น รำ สนุก ใจ กาย คล่อง แคล่ว", example:"Dance with joy!", exampleThai:"เต้นด้วยความสุข!", rhymeGroup:"ance" },
  { id:86, word:"play", phonetic:"/pleɪ/", thai:"เล่น", category:"actions", level:"A1", rhyme:"เล่น สนุก เฮฮา ยิ้ม แย้ม แจ่มใส", example:"Children love to play.", exampleThai:"เด็กๆ ชอบเล่น", rhymeGroup:"ay" },
  { id:87, word:"sleep", phonetic:"/sliːp/", thai:"นอนหลับ", category:"actions", level:"A1", rhyme:"นอน หลับ ฝัน ดี กลางคืน ยาว นาน", example:"Sleep well every night.", exampleThai:"นอนหลับพักผ่อนดีๆ ทุกคืน", rhymeGroup:"eep" },
  { id:88, word:"eat", phonetic:"/iːt/", thai:"กิน", category:"actions", level:"A1", rhyme:"กิน อาหาร อร่อย มาก ไม่ อิ่ม", example:"Eat healthy food!", exampleThai:"กินอาหารที่ดีต่อสุขภาพ!", rhymeGroup:"eat" },
  { id:89, word:"drink", phonetic:"/drɪŋk/", thai:"ดื่ม", category:"actions", level:"A1", rhyme:"ดื่ม น้ำ สะอาด ทุก วัน แข็งแรง", example:"Drink water every day.", exampleThai:"ดื่มน้ำทุกวัน", rhymeGroup:"ink" },
  { id:90, word:"smile", phonetic:"/smaɪl/", thai:"ยิ้ม", category:"actions", level:"A1", rhyme:"ยิ้ม หน้า ใส ใจ ดี มี เสน่ห์", example:"Smile and the world smiles back.", exampleThai:"ยิ้มและโลกจะยิ้มตอบ", rhymeGroup:"ile" },

  // Feelings
  { id:91, word:"happy", phonetic:"/ˈhæpi/", thai:"มีความสุข", category:"feelings", level:"A1", rhyme:"มี สุข ยิ้ม แย้ม แจ่มใส ทุก วัน", example:"I feel happy today.", exampleThai:"วันนี้ฉันมีความสุข", rhymeGroup:"y" },
  { id:92, word:"sad", phonetic:"/sæd/", thai:"เศร้า", category:"feelings", level:"A1", rhyme:"เศร้า นิด หน่อย แต่ พรุ่งนี้ ดี กว่า", example:"Don't be sad.", exampleThai:"อย่าเศร้านะ", rhymeGroup:"ad" },
  { id:93, word:"angry", phonetic:"/ˈæŋɡri/", thai:"โกรธ", category:"feelings", level:"A1", rhyme:"โกรธ แค่ น้อย แต่ ให้ อภัย กัน เถอะ", example:"Take a deep breath when angry.", exampleThai:"หายใจลึกๆ ตอนโกรธ", rhymeGroup:"y" },
  { id:94, word:"scared", phonetic:"/skerd/", thai:"กลัว", category:"feelings", level:"A1", rhyme:"กลัว นิด หน่อย แต่ กล้า ยิ่ง กว่า", example:"Don't be scared, be brave.", exampleThai:"อย่ากลัว จงกล้า", rhymeGroup:"ared" },
  { id:95, word:"love", phonetic:"/lʌv/", thai:"รัก", category:"feelings", level:"A1", rhyme:"รัก แท้ ไม่ เคย หมด ตลอด กาล", example:"Love makes the world better.", exampleThai:"ความรักทำให้โลกดีขึ้น", rhymeGroup:"ove" },
  { id:96, word:"kind", phonetic:"/kaɪnd/", thai:"ใจดี", category:"feelings", level:"A1", rhyme:"ใจ ดี แบ่ง ปัน ทุก สิ่ง มี คุณ ค่า", example:"Always be kind.", exampleThai:"จงใจดีเสมอ", rhymeGroup:"ind" },

  // A2 Words
  { id:97, word:"beautiful", phonetic:"/ˈbjuːtɪfəl/", thai:"สวยงาม", category:"adjectives", level:"A2", rhyme:"สวย งาม ดั่ง ดาว บน ฟ้า", example:"Nature is beautiful.", exampleThai:"ธรรมชาติสวยงาม", rhymeGroup:"ul" },
  { id:98, word:"important", phonetic:"/ɪmˈpɔːrtənt/", thai:"สำคัญ", category:"adjectives", level:"A2", rhyme:"สำคัญ ยิ่ง อย่า ลืม ทำ ดี", example:"Education is important.", exampleThai:"การศึกษาสำคัญมาก", rhymeGroup:"ant" },
  { id:99, word:"strong", phonetic:"/strɒŋ/", thai:"แข็งแรง", category:"adjectives", level:"A2", rhyme:"แข็ง แกร่ง กาย ใจ สู้ ไม่ ถอย", example:"Be strong every day.", exampleThai:"แข็งแกร่งทุกวัน", rhymeGroup:"ong" },
  { id:100, word:"brave", phonetic:"/breɪv/", thai:"กล้าหาญ", category:"adjectives", level:"A2", rhyme:"กล้า หาญ ยืน หยัด สู้ ทุก อุปสรรค", example:"Be brave and face your fears.", exampleThai:"จงกล้าหาญสู้กับความกลัว", rhymeGroup:"ave" },
  { id:101, word:"clean", phonetic:"/kliːn/", thai:"สะอาด", category:"adjectives", level:"A2", rhyme:"สะอาด บริสุทธิ์ ดี ต่อ สุขภาพ", example:"Keep your room clean.", exampleThai:"รักษาห้องให้สะอาด", rhymeGroup:"ean" },
  { id:102, word:"quiet", phonetic:"/ˈkwaɪət/", thai:"เงียบ", category:"adjectives", level:"A2", rhyme:"เงียบ สงบ ใจ นิ่ง คิด ได้ ชัด", example:"The library is quiet.", exampleThai:"ห้องสมุดเงียบ", rhymeGroup:"et" },
  { id:103, word:"bright", phonetic:"/braɪt/", thai:"สว่าง/ฉลาด", category:"adjectives", level:"A2", rhyme:"สว่าง ส่อง ทาง ไม่ ให้ หลง ทาง", example:"Your future is bright!", exampleThai:"อนาคตของคุณสดใส!", rhymeGroup:"ight" },
  { id:104, word:"funny", phonetic:"/ˈfʌni/", thai:"ตลก", category:"adjectives", level:"A2", rhyme:"ตลก ขำ ขัน หัวเราะ หาย เครียด", example:"He tells funny jokes.", exampleThai:"เขาเล่าเรื่องตลก", rhymeGroup:"y" },

  // More verbs A2
  { id:105, word:"help", phonetic:"/help/", thai:"ช่วยเหลือ", category:"actions", level:"A1", rhyme:"ช่วย กัน ไว้ โลก นี้ ดี ขึ้น", example:"Help someone today.", exampleThai:"ช่วยเหลือคนอื่นวันนี้เลย", rhymeGroup:"elp" },
  { id:106, word:"share", phonetic:"/ʃeər/", thai:"แบ่งปัน", category:"actions", level:"A1", rhyme:"แบ่ง ปัน ทุก สิ่ง ใจ กว้าง ดี งาม", example:"Share your food with friends.", exampleThai:"แบ่งอาหารให้เพื่อน", rhymeGroup:"are" },
  { id:107, word:"think", phonetic:"/θɪŋk/", thai:"คิด", category:"actions", level:"A1", rhyme:"คิด ดี ก่อน ทำ ดี กว่า แก้ ทีหลัง", example:"Think before you speak.", exampleThai:"คิดก่อนพูด", rhymeGroup:"ink" },
  { id:108, word:"try", phonetic:"/traɪ/", thai:"พยายาม", category:"actions", level:"A1", rhyme:"พยายาม ทำ ดี ที่สุด ทุก วัน ไป", example:"Always try your best.", exampleThai:"พยายามทำดีที่สุดเสมอ", rhymeGroup:"y" },
  { id:109, word:"grow", phonetic:"/ɡroʊ/", thai:"เติบโต", category:"actions", level:"A2", rhyme:"เติบ โต ทุก วัน ดั่ง ต้นไม้ ใหญ่", example:"Plants grow with water.", exampleThai:"ต้นไม้เติบโตด้วยน้ำ", rhymeGroup:"ow" },
  { id:110, word:"dream", phonetic:"/driːm/", thai:"ฝัน", category:"actions", level:"A2", rhyme:"ฝัน ให้ ไกล แล้ว ไป ถึง ดาว สูง", example:"Dream big, work hard!", exampleThai:"ฝันให้ใหญ่ แล้วทำงานหนัก!", rhymeGroup:"eam" },

  // More nature A2
  { id:111, word:"forest", phonetic:"/ˈfɒrɪst/", thai:"ป่า", category:"nature", level:"A2", rhyme:"ป่า ใหญ่ ร่ม เย็น สัตว์ นก อาศัย", example:"The forest is full of animals.", exampleThai:"ป่าเต็มไปด้วยสัตว์ต่างๆ", rhymeGroup:"est" },
  { id:112, word:"ocean", phonetic:"/ˈoʊʃən/", thai:"มหาสมุทร", category:"nature", level:"A2", rhyme:"มหา สมุทร กว้าง ใหญ่ ลึก ล้น ฝัน", example:"The ocean covers most of Earth.", exampleThai:"มหาสมุทรครอบคลุมโลกส่วนใหญ่", rhymeGroup:"an" },
  { id:113, word:"desert", phonetic:"/ˈdezərt/", thai:"ทะเลทราย", category:"nature", level:"A2", rhyme:"ทะเล ทราย ร้อน แรง แต่ สวย งาม", example:"Camels live in the desert.", exampleThai:"อูฐอาศัยอยู่ในทะเลทราย", rhymeGroup:"ert" },
  { id:114, word:"island", phonetic:"/ˈaɪlənd/", thai:"เกาะ", category:"nature", level:"A2", rhyme:"เกาะ เล็ก กลาง ทะเล สวย งาม ไม่มี เปรียบ", example:"The island is surrounded by water.", exampleThai:"เกาะล้อมรอบด้วยน้ำ", rhymeGroup:"and" },
  { id:115, word:"volcano", phonetic:"/vɒlˈkeɪnoʊ/", thai:"ภูเขาไฟ", category:"nature", level:"A2", rhyme:"ภูเขา ไฟ ร้อน แรง พุ่ง ขึ้น ฟ้า", example:"The volcano erupted.", exampleThai:"ภูเขาไฟระเบิด", rhymeGroup:"o" },

  // Daily life A2
  { id:116, word:"morning", phonetic:"/ˈmɔːrnɪŋ/", thai:"เช้า", category:"time", level:"A1", rhyme:"เช้า ตรู่ ลืม ตา ดู ฟ้า สว่าง", example:"Good morning everyone!", exampleThai:"อรุณสวัสดิ์ทุกคน!", rhymeGroup:"ing" },
  { id:117, word:"night", phonetic:"/naɪt/", thai:"กลางคืน", category:"time", level:"A1", rhyme:"กลาง คืน ดาว พราว ฟ้า ฝัน ดี", example:"Good night, sleep tight!", exampleThai:"ราตรีสวัสดิ์ นอนหลับฝันดี!", rhymeGroup:"ight" },
  { id:118, word:"today", phonetic:"/təˈdeɪ/", thai:"วันนี้", category:"time", level:"A1", rhyme:"วัน นี้ ดี ที่สุด ทำ ดี ไว้", example:"Today is a good day.", exampleThai:"วันนี้เป็นวันที่ดี", rhymeGroup:"ay" },
  { id:119, word:"week", phonetic:"/wiːk/", thai:"สัปดาห์", category:"time", level:"A1", rhyme:"หนึ่ง สัปดาห์ เจ็ด วัน ทำ ดี ทุก วัน", example:"There are 7 days in a week.", exampleThai:"หนึ่งสัปดาห์มี 7 วัน", rhymeGroup:"eek" },
  { id:120, word:"year", phonetic:"/jɪər/", thai:"ปี", category:"time", level:"A1", rhyme:"ปี ใหม่ มา แล้ว ฝัน ใหม่ เริ่ม ใหม่", example:"Happy New Year!", exampleThai:"สวัสดีปีใหม่!", rhymeGroup:"ear" },

  // A1 - Numbers
  { id:121, word:"one", phonetic:"/wʌn/", thai:"หนึ่ง", category:"numbers", level:"A1", rhyme:"หนึ่ง คือ จุด เริ่ม ต้น ของ ทุก สิ่ง", example:"I have one sister.", exampleThai:"ฉันมีน้องสาวหนึ่งคน", rhymeGroup:"un" },
  { id:122, word:"two", phonetic:"/tuː/", thai:"สอง", category:"numbers", level:"A1", rhyme:"สอง มือ จับ ต้อง สร้าง สิ่ง ดี งาม", example:"I have two hands.", exampleThai:"ฉันมีสองมือ", rhymeGroup:"oo" },
  { id:123, word:"three", phonetic:"/θriː/", thai:"สาม", category:"numbers", level:"A1", rhyme:"สาม สี่ ห้า นับ ต่อ ไป สนุก", example:"There are three cats.", exampleThai:"มีแมวสามตัว", rhymeGroup:"ee" },
  { id:124, word:"four", phonetic:"/fɔːr/", thai:"สี่", category:"numbers", level:"A1", rhyme:"สี่ ขา สัตว์ เดิน ไป ไม่ หยุด", example:"Dogs have four legs.", exampleThai:"สุนัขมีสี่ขา", rhymeGroup:"our" },
  { id:125, word:"five", phonetic:"/faɪv/", thai:"ห้า", category:"numbers", level:"A1", rhyme:"ห้า นิ้ว มือ ทำ งาน ดี ทุก วัน", example:"I have five fingers.", exampleThai:"ฉันมีนิ้วห้านิ้ว", rhymeGroup:"ive" },
  { id:126, word:"ten", phonetic:"/ten/", thai:"สิบ", category:"numbers", level:"A1", rhyme:"สิบ นิ้ว มือ เท้า รวม กัน สร้าง สรรค์", example:"Count to ten.", exampleThai:"นับถึงสิบ", rhymeGroup:"en" },
  { id:127, word:"hundred", phonetic:"/ˈhʌndrəd/", thai:"ร้อย", category:"numbers", level:"A1", rhyme:"ร้อย วัน ผ่าน ไป ยัง รัก เท่า เดิม", example:"There are one hundred students.", exampleThai:"มีนักเรียนหนึ่งร้อยคน", rhymeGroup:"ed" },

  // A1 - Common adjectives
  { id:128, word:"big", phonetic:"/bɪɡ/", thai:"ใหญ่", category:"adjectives", level:"A1", rhyme:"ใหญ่ โต แข็งแกร่ง ดั่ง ช้าง สง่า งาม", example:"An elephant is very big.", exampleThai:"ช้างตัวใหญ่มาก", rhymeGroup:"ig" },
  { id:129, word:"small", phonetic:"/smɔːl/", thai:"เล็ก", category:"adjectives", level:"A1", rhyme:"เล็ก น้อย แต่ ก็ มี คุณค่า มาก", example:"Ants are small but strong.", exampleThai:"มดตัวเล็กแต่แข็งแรง", rhymeGroup:"all" },
  { id:130, word:"long", phonetic:"/lɒŋ/", thai:"ยาว", category:"adjectives", level:"A1", rhyme:"ยาว ไกล แต่ ก็ ถึง จุด หมาย ได้", example:"The snake is very long.", exampleThai:"งูยาวมาก", rhymeGroup:"ong" },
  { id:131, word:"short", phonetic:"/ʃɔːt/", thai:"สั้น/เตี้ย", category:"adjectives", level:"A1", rhyme:"สั้น แต่ กระชับ ดี ได้ ใจ ความ", example:"My hair is short.", exampleThai:"ผมของฉันสั้น", rhymeGroup:"ort" },
  { id:132, word:"new", phonetic:"/njuː/", thai:"ใหม่", category:"adjectives", level:"A1", rhyme:"ใหม่ ๆ สด ชื่น ดี กว่า เดิม", example:"I have a new book.", exampleThai:"ฉันมีหนังสือเล่มใหม่", rhymeGroup:"ew" },
  { id:133, word:"old", phonetic:"/oʊld/", thai:"เก่า/แก่", category:"adjectives", level:"A1", rhyme:"เก่า แก่ มี คุณ ค่า แสน ล้ำ", example:"This is an old building.", exampleThai:"นี่คืออาคารเก่า", rhymeGroup:"old" },
  { id:134, word:"good", phonetic:"/ɡʊd/", thai:"ดี", category:"adjectives", level:"A1", rhyme:"ดี ใจ ทำ ดี ได้ รับ ดี เสมอ", example:"Be a good person.", exampleThai:"จงเป็นคนดี", rhymeGroup:"ood" },
  { id:135, word:"bad", phonetic:"/bæd/", thai:"ไม่ดี/เลว", category:"adjectives", level:"A1", rhyme:"ไม่ ดี ก็ แก้ ไข ใหม่ ให้ ดี กว่า", example:"Bad habits are hard to break.", exampleThai:"นิสัยที่ไม่ดีเลิกยาก", rhymeGroup:"ad" },
  { id:136, word:"hot", phonetic:"/hɒt/", thai:"ร้อน", category:"adjectives", level:"A1", rhyme:"ร้อน แรง ดั่ง ไฟ ลุก สว่าง ฟ้า", example:"The sun is very hot.", exampleThai:"ดวงอาทิตย์ร้อนมาก", rhymeGroup:"ot" },
  { id:137, word:"cold", phonetic:"/koʊld/", thai:"เย็น/หนาว", category:"adjectives", level:"A1", rhyme:"หนาว เย็น ลม พัด ชื่น สดชื่น ดี", example:"Winter is cold.", exampleThai:"ฤดูหนาวอากาศหนาว", rhymeGroup:"old" },
  { id:138, word:"fast", phonetic:"/fɑːst/", thai:"เร็ว", category:"adjectives", level:"A1", rhyme:"เร็ว ดั่ง สายฟ้า ฟาด ไม่ มี ใด เทียบ", example:"Cheetahs run fast.", exampleThai:"เสือชีตาวิ่งเร็วมาก", rhymeGroup:"ast" },
  { id:139, word:"slow", phonetic:"/sloʊ/", thai:"ช้า", category:"adjectives", level:"A1", rhyme:"ช้า ๆ ได้ พร้าว เล่ม งาม ค่อย ๆ ดี", example:"Turtles move slowly.", exampleThai:"เต่าเคลื่อนที่ช้า", rhymeGroup:"ow" },
  { id:140, word:"tall", phonetic:"/tɔːl/", thai:"สูง", category:"adjectives", level:"A1", rhyme:"สูง ตระหง่าน ดั่ง ภูเขา ไม่ หวั่น", example:"Giraffes are very tall.", exampleThai:"ยีราฟสูงมาก", rhymeGroup:"all" },

  // A1 - Common verbs
  { id:141, word:"go", phonetic:"/ɡoʊ/", thai:"ไป", category:"actions", level:"A1", rhyme:"ไป ให้ ถึง ฝัน อย่า หยุด ไม่ ถอย", example:"Let's go to school!", exampleThai:"ไปโรงเรียนกันเถอะ!", rhymeGroup:"o" },
  { id:142, word:"come", phonetic:"/kʌm/", thai:"มา", category:"actions", level:"A1", rhyme:"มา แล้ว นะ รอ ด้วย ใจ จดจ่อ", example:"Come here, please.", exampleThai:"มาที่นี่หน่อยนะ", rhymeGroup:"um" },
  { id:143, word:"see", phonetic:"/siː/", thai:"มอง/เห็น", category:"actions", level:"A1", rhyme:"มอง เห็น โลก กว้าง ใหญ่ สวย งาม", example:"I can see the stars.", exampleThai:"ฉันมองเห็นดาว", rhymeGroup:"ee" },
  { id:144, word:"know", phonetic:"/noʊ/", thai:"รู้/รู้จัก", category:"actions", level:"A1", rhyme:"รู้ มาก ยิ่ง ดี เรียน รู้ ไม่ สิ้น สุด", example:"Do you know the answer?", exampleThai:"คุณรู้คำตอบไหม?", rhymeGroup:"ow" },
  { id:145, word:"want", phonetic:"/wɒnt/", thai:"ต้องการ/อยากได้", category:"actions", level:"A1", rhyme:"อยาก ได้ ก็ ต้อง ลงมือ ทำ", example:"I want to be a doctor.", exampleThai:"ฉันอยากเป็นหมอ", rhymeGroup:"ont" },
  { id:146, word:"get", phonetic:"/ɡet/", thai:"ได้รับ/ไปหยิบ", category:"actions", level:"A1", rhyme:"ได้ รับ แล้ว ต้อง ขอบคุณ เสมอ", example:"Get your coat, it's cold.", exampleThai:"เอาเสื้อโค้ตมา อากาศหนาว", rhymeGroup:"et" },
  { id:147, word:"make", phonetic:"/meɪk/", thai:"ทำ/สร้าง", category:"actions", level:"A1", rhyme:"ทำ สิ่ง ดี สร้าง โลก ให้ งดงาม", example:"Let's make a cake!", exampleThai:"มาทำเค้กกัน!", rhymeGroup:"ake" },
  { id:148, word:"give", phonetic:"/ɡɪv/", thai:"ให้", category:"actions", level:"A1", rhyme:"ให้ ด้วย ใจ กว้าง ดี ที่สุด", example:"Give love to everyone.", exampleThai:"มอบความรักให้ทุกคน", rhymeGroup:"iv" },
  { id:149, word:"take", phonetic:"/teɪk/", thai:"เอา/พา", category:"actions", level:"A1", rhyme:"หยิบ เอา ไป ใช้ ให้ คุ้มค่า", example:"Take your time.", exampleThai:"ค่อยๆ ทำไป ไม่ต้องรีบ", rhymeGroup:"ake" },
  { id:150, word:"love", phonetic:"/lʌv/", thai:"รัก (กริยา)", category:"actions", level:"A1", rhyme:"รัก ใคร ก็ บอก ไป อย่า รอ นาน", example:"I love you.", exampleThai:"ฉันรักคุณ", rhymeGroup:"ov" },

  // A2 - Places
  { id:151, word:"restaurant", phonetic:"/ˈrestrɒnt/", thai:"ร้านอาหาร", category:"places", level:"A2", rhyme:"ร้าน อาหาร อร่อย กลิ่น หอม โชย มา", example:"Let's eat at a restaurant.", exampleThai:"ไปกินอาหารที่ร้านกันเถอะ", rhymeGroup:"ant" },
  { id:152, word:"hospital", phonetic:"/ˈhɒspɪtəl/", thai:"โรงพยาบาล", category:"places", level:"A2", rhyme:"โรง พยาบาล ดูแล คน ป่วย ด้วย ใจ", example:"The hospital helps sick people.", exampleThai:"โรงพยาบาลช่วยเหลือคนป่วย", rhymeGroup:"al" },
  { id:153, word:"airport", phonetic:"/ˈeəpɔːt/", thai:"สนามบิน", category:"places", level:"A2", rhyme:"สนาม บิน พา ฝัน ไป ถึง ทั่ว โลก", example:"We go to the airport by taxi.", exampleThai:"เราไปสนามบินด้วยแท็กซี่", rhymeGroup:"ort" },
  { id:154, word:"market", phonetic:"/ˈmɑːkɪt/", thai:"ตลาด", category:"places", level:"A1", rhyme:"ตลาด คึกคัก สด ใหม่ หลาก สีสัน", example:"Buy fresh food at the market.", exampleThai:"ซื้ออาหารสดที่ตลาด", rhymeGroup:"et" },
  { id:155, word:"park", phonetic:"/pɑːk/", thai:"สวนสาธารณะ", category:"places", level:"A1", rhyme:"สวน สาธารณะ เขียว ขจี ร่ม เย็น", example:"Children play at the park.", exampleThai:"เด็กๆ เล่นที่สวนสาธารณะ", rhymeGroup:"ark" },
  { id:156, word:"library", phonetic:"/ˈlaɪbrəri/", thai:"ห้องสมุด", category:"places", level:"A1", rhyme:"ห้อง สมุด เงียบ สงบ เต็ม ความ รู้", example:"I study in the library.", exampleThai:"ฉันอ่านหนังสือในห้องสมุด", rhymeGroup:"y" },
  { id:157, word:"hotel", phonetic:"/hoʊˈtel/", thai:"โรงแรม", category:"places", level:"A1", rhyme:"โรง แรม หรู หรา ต้อน รับ แขก ดี", example:"We stay at a nice hotel.", exampleThai:"เราพักที่โรงแรมดีๆ", rhymeGroup:"el" },
  { id:158, word:"museum", phonetic:"/mjuːˈziːəm/", thai:"พิพิธภัณฑ์", category:"places", level:"A2", rhyme:"พิพิธภัณฑ์ เก็บ ความ รู้ ประวัติ ศาสตร์", example:"The museum has old paintings.", exampleThai:"พิพิธภัณฑ์มีภาพวาดเก่าแก่", rhymeGroup:"um" },
  { id:159, word:"bank", phonetic:"/bæŋk/", thai:"ธนาคาร", category:"places", level:"A1", rhyme:"ธนาคาร เก็บ เงิน ทอง ปลอดภัย", example:"Save money at the bank.", exampleThai:"ฝากเงินที่ธนาคาร", rhymeGroup:"ank" },
  { id:160, word:"office", phonetic:"/ˈɒfɪs/", thai:"สำนักงาน", category:"places", level:"A1", rhyme:"ออ ฟิศ ทำ งาน รุ่ง เรือง สู่ เป้า หมาย", example:"My dad works in an office.", exampleThai:"พ่อทำงานที่สำนักงาน", rhymeGroup:"is" },

  // A2 - Technology
  { id:161, word:"phone", phonetic:"/foʊn/", thai:"โทรศัพท์", category:"technology", level:"A1", rhyme:"โทรศัพท์ ติด ต่อ ทุก ที่ ไม่ ห่าง", example:"Call me on my phone.", exampleThai:"โทรหาฉันทางโทรศัพท์นะ", rhymeGroup:"one" },
  { id:162, word:"computer", phonetic:"/kəmˈpjuːtər/", thai:"คอมพิวเตอร์", category:"technology", level:"A1", rhyme:"คอม พิว เตอร์ ช่วย งาน สะดวก รวดเร็ว", example:"I use a computer for work.", exampleThai:"ฉันใช้คอมพิวเตอร์ทำงาน", rhymeGroup:"er" },
  { id:163, word:"internet", phonetic:"/ˈɪntənet/", thai:"อินเทอร์เน็ต", category:"technology", level:"A1", rhyme:"อิน เทอร์ เน็ต เชื่อม โลก ทั้ง ใบ ไว้ ด้วย กัน", example:"Use the internet carefully.", exampleThai:"ใช้อินเทอร์เน็ตอย่างระมัดระวัง", rhymeGroup:"et" },
  { id:164, word:"camera", phonetic:"/ˈkæmərə/", thai:"กล้องถ่ายรูป", category:"technology", level:"A1", rhyme:"กล้อง ถ่าย รูป เก็บ ความ ทรงจำ ดี งาม", example:"Smile for the camera!", exampleThai:"ยิ้มให้กล้องด้วยนะ!", rhymeGroup:"a" },
  { id:165, word:"television", phonetic:"/ˈtelɪvɪʒn/", thai:"โทรทัศน์", category:"technology", level:"A1", rhyme:"โทรทัศน์ ดู ข่าว บันเทิง พัก ผ่อน", example:"We watch television together.", exampleThai:"เราดูโทรทัศน์ด้วยกัน", rhymeGroup:"on" },

  // A2 - Clothes
  { id:166, word:"shirt", phonetic:"/ʃɜːt/", thai:"เสื้อเชิ้ต", category:"clothes", level:"A1", rhyme:"เสื้อ เชิ้ต ใส่ สบาย ดู ดี น่า รัก", example:"He wears a white shirt.", exampleThai:"เขาใส่เสื้อเชิ้ตสีขาว", rhymeGroup:"irt" },
  { id:167, word:"dress", phonetic:"/dres/", thai:"ชุดกระโปรง", category:"clothes", level:"A1", rhyme:"ชุด กระโปรง สวย งาม ดั่ง เจ้า หญิง", example:"She wears a beautiful dress.", exampleThai:"เธอใส่ชุดกระโปรงสวยๆ", rhymeGroup:"ess" },
  { id:168, word:"shoes", phonetic:"/ʃuːz/", thai:"รองเท้า", category:"clothes", level:"A1", rhyme:"รองเท้า ใส่ ก้าว เดิน ไป ข้าง หน้า", example:"Put on your shoes.", exampleThai:"ใส่รองเท้าด้วย", rhymeGroup:"oos" },
  { id:169, word:"hat", phonetic:"/hæt/", thai:"หมวก", category:"clothes", level:"A1", rhyme:"หมวก ใส่ กัน แดด กัน ฝน ดี นัก", example:"Wear a hat in the sun.", exampleThai:"ใส่หมวกตอนออกแดด", rhymeGroup:"at" },
  { id:170, word:"jacket", phonetic:"/ˈdʒækɪt/", thai:"แจ็คเก็ต", category:"clothes", level:"A1", rhyme:"แจ็ค เก็ต ใส่ กัน หนาว อุ่น ดี นัก", example:"Wear a jacket when it's cold.", exampleThai:"ใส่แจ็คเก็ตตอนอากาศหนาว", rhymeGroup:"et" },

  // A2 - Sports & Activities
  { id:171, word:"sport", phonetic:"/spɔːt/", thai:"กีฬา", category:"sports", level:"A1", rhyme:"กีฬา สร้าง สุขภาพ ดี แข็งแรง ทุก วัน", example:"Sport keeps you healthy.", exampleThai:"กีฬาทำให้สุขภาพดี", rhymeGroup:"ort" },
  { id:172, word:"football", phonetic:"/ˈfʊtbɔːl/", thai:"ฟุตบอล", category:"sports", level:"A1", rhyme:"ฟุต บอล เตะ ดัง โกล์ เข้า ชนะ", example:"Football is popular worldwide.", exampleThai:"ฟุตบอลเป็นที่นิยมทั่วโลก", rhymeGroup:"all" },
  { id:173, word:"tennis", phonetic:"/ˈtenɪs/", thai:"เทนนิส", category:"sports", level:"A1", rhyme:"เท น นิส ตี ลูก ไป มา สนุก ดี", example:"Let's play tennis!", exampleThai:"ไปเล่นเทนนิสกัน!", rhymeGroup:"is" },
  { id:174, word:"music", phonetic:"/ˈmjuːzɪk/", thai:"ดนตรี", category:"arts", level:"A1", rhyme:"ดนตรี ไพเราะ ชื่น ใจ จิตใจ สงบ", example:"Music makes me happy.", exampleThai:"ดนตรีทำให้ฉันมีความสุข", rhymeGroup:"ic" },
  { id:175, word:"art", phonetic:"/ɑːt/", thai:"ศิลปะ", category:"arts", level:"A1", rhyme:"ศิลปะ งาม ตา งาม ใจ ไม่ มี ที่สิ้น สุด", example:"Art expresses feelings.", exampleThai:"ศิลปะแสดงออกถึงความรู้สึก", rhymeGroup:"art" },

  // A2 - Food extras
  { id:176, word:"chicken", phonetic:"/ˈtʃɪkɪn/", thai:"ไก่", category:"food", level:"A1", rhyme:"ไก่ ย่าง หอม กลิ่น ชวน กิน แสน อร่อย", example:"I like chicken soup.", exampleThai:"ฉันชอบซุปไก่", rhymeGroup:"en" },
  { id:177, word:"meat", phonetic:"/miːt/", thai:"เนื้อสัตว์", category:"food", level:"A1", rhyme:"เนื้อ สัตว์ ปรุง ดี มีรส ชาติ อร่อย", example:"Some people don't eat meat.", exampleThai:"บางคนไม่กินเนื้อสัตว์", rhymeGroup:"eat" },
  { id:178, word:"vegetable", phonetic:"/ˈvedʒtəbəl/", thai:"ผัก", category:"food", level:"A1", rhyme:"ผัก สด สี เขียว ดี ต่อ สุขภาพ", example:"Eat your vegetables!", exampleThai:"กินผักด้วยนะ!", rhymeGroup:"le" },
  { id:179, word:"fruit", phonetic:"/fruːt/", thai:"ผลไม้", category:"food", level:"A1", rhyme:"ผล ไม้ หวาน สด ชื่น ชวน กิน ทุก วัน", example:"Fruit is sweet and healthy.", exampleThai:"ผลไม้หวานและดีต่อสุขภาพ", rhymeGroup:"oot" },
  { id:180, word:"coffee", phonetic:"/ˈkɒfi/", thai:"กาแฟ", category:"food", level:"A1", rhyme:"กา แฟ หอม กลิ่น ตื่น ตัว สดชื่น ดี", example:"Morning coffee wakes me up.", exampleThai:"กาแฟยามเช้าทำให้ตื่นตัว", rhymeGroup:"y" },
  { id:181, word:"sugar", phonetic:"/ˈʃʊɡər/", thai:"น้ำตาล", category:"food", level:"A1", rhyme:"น้ำ ตาล หวาน ชื่น ใจ แต่ อย่า มาก เกิน", example:"Don't eat too much sugar.", exampleThai:"อย่ากินน้ำตาลมากเกินไป", rhymeGroup:"ar" },
  { id:182, word:"salt", phonetic:"/sɔːlt/", thai:"เกลือ", category:"food", level:"A1", rhyme:"เกลือ เค็ม นิด หน่อย รส ชาติ ดี ขึ้น", example:"Add a little salt.", exampleThai:"ใส่เกลือนิดหน่อย", rhymeGroup:"alt" },
  { id:183, word:"chocolate", phonetic:"/ˈtʃɒklət/", thai:"ช็อกโกแลต", category:"food", level:"A1", rhyme:"ช็อก โก แลต หวาน มัน ละลาย ใน ปาก", example:"I love dark chocolate.", exampleThai:"ฉันชอบช็อกโกแลตดำ", rhymeGroup:"et" },

  // B1 - Emotions & Personality
  { id:184, word:"excited", phonetic:"/ɪkˈsaɪtɪd/", thai:"ตื่นเต้น", category:"feelings", level:"A1", rhyme:"ตื่น เต้น ใจ เต้น แรง รอ สิ่ง ดี มา", example:"I'm excited about my birthday!", exampleThai:"ฉันตื่นเต้นกับวันเกิด!", rhymeGroup:"ed" },
  { id:185, word:"tired", phonetic:"/ˈtaɪəd/", thai:"เหนื่อย", category:"feelings", level:"A1", rhyme:"เหนื่อย แล้ว ก็ พัก แล้ว ลุก ขึ้น ใหม่", example:"I feel tired after running.", exampleThai:"ฉันเหนื่อยหลังจากวิ่ง", rhymeGroup:"ired" },
  { id:186, word:"bored", phonetic:"/bɔːd/", thai:"เบื่อ", category:"feelings", level:"A1", rhyme:"เบื่อ ก็ หา สิ่ง ใหม่ ทำ ได้ เลย", example:"I'm bored. Let's play!", exampleThai:"ฉันเบื่อแล้ว ไปเล่นกันเถอะ!", rhymeGroup:"ored" },
  { id:187, word:"surprised", phonetic:"/səˈpraɪzd/", thai:"แปลกใจ", category:"feelings", level:"A2", rhyme:"แปลก ใจ ทำ ตา โต ยิ้ม กว้าง ทั่ว หน้า", example:"I was surprised by the gift.", exampleThai:"ฉันแปลกใจกับของขวัญ", rhymeGroup:"ized" },
  { id:188, word:"nervous", phonetic:"/ˈnɜːvəs/", thai:"กังวล/ตื่นเต้น", category:"feelings", level:"A2", rhyme:"กังวล นิด หน่อย แต่ สู้ ได้ ทุก อย่าง", example:"I feel nervous before exams.", exampleThai:"ฉันกังวลก่อนสอบ", rhymeGroup:"us" },
  { id:189, word:"proud", phonetic:"/praʊd/", thai:"ภูมิใจ", category:"feelings", level:"B1", rhyme:"ภูมิ ใจ ใน ตัว เอง และ ครอบครัว", example:"I'm proud of my work.", exampleThai:"ฉันภูมิใจในงานของฉัน", rhymeGroup:"oud" },
  { id:190, word:"lonely", phonetic:"/ˈloʊnli/", thai:"เหงา", category:"feelings", level:"B1", rhyme:"เหงา ก็ โทร หา เพื่อน คุย สบาย ใจ", example:"Don't feel lonely, call a friend.", exampleThai:"อย่าเหงา โทรหาเพื่อนสิ", rhymeGroup:"y" },
  { id:191, word:"patient", phonetic:"/ˈpeɪʃnt/", thai:"อดทน", category:"adjectives", level:"B1", rhyme:"อด ทน รอ ได้ ผล ดี กว่า เสมอ", example:"Be patient and wait.", exampleThai:"จงอดทนและรอ", rhymeGroup:"ent" },
  { id:192, word:"confident", phonetic:"/ˈkɒnfɪdənt/", thai:"มั่นใจ", category:"adjectives", level:"B1", rhyme:"มั่น ใจ ใน ตัว เอง แล้ว ก้าว ไป", example:"Be confident in yourself.", exampleThai:"จงมั่นใจในตัวเอง", rhymeGroup:"ent" },
  { id:193, word:"creative", phonetic:"/kriˈeɪtɪv/", thai:"สร้างสรรค์", category:"adjectives", level:"B1", rhyme:"สร้าง สรรค์ ไม่ หยุด คิด ใหม่ ทุก วัน", example:"She is very creative.", exampleThai:"เธอสร้างสรรค์มาก", rhymeGroup:"ive" },
  { id:194, word:"honest", phonetic:"/ˈɒnɪst/", thai:"ซื่อสัตย์", category:"adjectives", level:"B1", rhyme:"ซื่อ สัตย์ ไว้ ใจ ได้ ดี ที่สุด", example:"Always be honest.", exampleThai:"จงซื่อสัตย์เสมอ", rhymeGroup:"est" },
  { id:195, word:"generous", phonetic:"/ˈdʒenərəs/", thai:"ใจกว้าง", category:"adjectives", level:"B1", rhyme:"ใจ กว้าง แบ่ง ปัน ดี ทำ โลก สวย งาม", example:"She is very generous.", exampleThai:"เธอใจกว้างมาก", rhymeGroup:"us" },

  // B1 - Work & Career
  { id:196, word:"job", phonetic:"/dʒɒb/", thai:"งาน", category:"work", level:"A1", rhyme:"งาน ดี มี ความ สุข ทำ ด้วย ใจ", example:"I have a good job.", exampleThai:"ฉันมีงานที่ดี", rhymeGroup:"ob" },
  { id:197, word:"work", phonetic:"/wɜːk/", thai:"ทำงาน", category:"work", level:"A1", rhyme:"ทำ งาน ขยัน ดี ผล ออก มา งาม", example:"Work hard every day.", exampleThai:"ทำงานหนักทุกวัน", rhymeGroup:"ork" },
  { id:198, word:"money", phonetic:"/ˈmʌni/", thai:"เงิน", category:"work", level:"A1", rhyme:"เงิน มา จาก น้ำ พักน้ำ แรง ขยัน", example:"Save your money wisely.", exampleThai:"เก็บเงินอย่างฉลาด", rhymeGroup:"y" },
  { id:199, word:"doctor", phonetic:"/ˈdɒktər/", thai:"หมอ", category:"work", level:"A1", rhyme:"หมอ รักษา คน ป่วย ด้วย ใจ เมตตา", example:"The doctor helps sick people.", exampleThai:"หมอช่วยเหลือคนป่วย", rhymeGroup:"er" },
  { id:200, word:"nurse", phonetic:"/nɜːs/", thai:"พยาบาล", category:"work", level:"A1", rhyme:"พยาบาล ดูแล คน ไข้ ด้วย ใจ อ่อน โยน", example:"The nurse is very kind.", exampleThai:"พยาบาลใจดีมาก", rhymeGroup:"urse" },
  { id:201, word:"engineer", phonetic:"/ˌendʒɪˈnɪər/", thai:"วิศวกร", category:"work", level:"A2", rhyme:"วิศวกร สร้าง สิ่ง ใหม่ เปลี่ยน โลก ให้ ดี", example:"Engineers build bridges.", exampleThai:"วิศวกรสร้างสะพาน", rhymeGroup:"eer" },
  { id:202, word:"artist", phonetic:"/ˈɑːtɪst/", thai:"ศิลปิน", category:"work", level:"A1", rhyme:"ศิลปิน วาด ฝัน ลง บน ผืน ผ้าใบ", example:"The artist paints beautiful pictures.", exampleThai:"ศิลปินวาดภาพสวยๆ", rhymeGroup:"ist" },
  { id:203, word:"musician", phonetic:"/mjuːˈzɪʃn/", thai:"นักดนตรี", category:"work", level:"A2", rhyme:"นัก ดนตรี เล่น เพลง ให้ โลก ชื่น ใจ", example:"The musician plays guitar.", exampleThai:"นักดนตรีเล่นกีตาร์", rhymeGroup:"an" },
  { id:204, word:"journalist", phonetic:"/ˈdʒɜːnəlɪst/", thai:"นักข่าว", category:"work", level:"A2", rhyme:"นัก ข่าว รายงาน ความ จริง แก่ สังคม", example:"The journalist writes news.", exampleThai:"นักข่าวเขียนข่าว", rhymeGroup:"ist" },

  // B1 - Health
  { id:205, word:"health", phonetic:"/helθ/", thai:"สุขภาพ", category:"health", level:"A1", rhyme:"สุข ภาพ ดี ชีวิต มี ความ สุข เสมอ", example:"Good health is very important.", exampleThai:"สุขภาพดีสำคัญมาก", rhymeGroup:"ealth" },
  { id:206, word:"medicine", phonetic:"/ˈmedsn/", thai:"ยา", category:"health", level:"A2", rhyme:"ยา รักษา โรค ให้ หาย แข็งแรง ดี", example:"Take your medicine every day.", exampleThai:"กินยาทุกวันนะ", rhymeGroup:"ine" },
  { id:207, word:"exercise", phonetic:"/ˈeksəsaɪz/", thai:"ออกกำลังกาย", category:"health", level:"A1", rhyme:"ออก กำลัง กาย ทุก วัน แข็งแรง สุขสันต์", example:"Exercise every morning.", exampleThai:"ออกกำลังกายทุกเช้า", rhymeGroup:"ise" },
  { id:208, word:"diet", phonetic:"/ˈdaɪət/", thai:"อาหารการกิน", category:"health", level:"A2", rhyme:"กิน อาหาร ดี มี ประโยชน์ ต่อ ร่างกาย", example:"A healthy diet is important.", exampleThai:"อาหารที่ดีต่อสุขภาพสำคัญมาก", rhymeGroup:"et" },
  { id:209, word:"sleep", phonetic:"/sliːp/", thai:"การนอนหลับ", category:"health", level:"A1", rhyme:"นอน หลับ พัก ผ่อน ให้ เพียง พอ สดชื่น", example:"Get enough sleep every night.", exampleThai:"นอนหลับให้เพียงพอทุกคืน", rhymeGroup:"eep" },

  // B1 - Environment
  { id:210, word:"environment", phonetic:"/ɪnˈvaɪrənmənt/", thai:"สิ่งแวดล้อม", category:"environment", level:"B1", rhyme:"สิ่ง แวด ล้อม ดี ชีวิต ดี ไป ด้วย", example:"Protect the environment.", exampleThai:"ปกป้องสิ่งแวดล้อม", rhymeGroup:"ent" },
  { id:211, word:"pollution", phonetic:"/pəˈluːʃn/", thai:"มลพิษ", category:"environment", level:"A2", rhyme:"มล พิษ ทำ โลก ป่วย ต้อง ช่วย กัน แก้", example:"Air pollution is dangerous.", exampleThai:"มลพิษทางอากาศอันตราย", rhymeGroup:"on" },
  { id:212, word:"recycle", phonetic:"/ˌriːˈsaɪkl/", thai:"รีไซเคิล", category:"environment", level:"A2", rhyme:"รี ไซ เคิล ช่วย โลก ให้ สะอาด ดี งาม", example:"Recycle plastic and paper.", exampleThai:"รีไซเคิลพลาสติกและกระดาษ", rhymeGroup:"le" },
  { id:213, word:"climate", phonetic:"/ˈklaɪmət/", thai:"ภูมิอากาศ", category:"environment", level:"B1", rhyme:"ภูมิ อากาศ เปลี่ยน แปลง ต้อง ช่วย กัน รักษา", example:"Climate change affects everyone.", exampleThai:"การเปลี่ยนแปลงภูมิอากาศส่งผลต่อทุกคน", rhymeGroup:"ate" },
  { id:214, word:"energy", phonetic:"/ˈenədʒi/", thai:"พลังงาน", category:"environment", level:"B1", rhyme:"พลัง งาน สะอาด ช่วย โลก ได้ ดี มาก", example:"Save energy every day.", exampleThai:"ประหยัดพลังงานทุกวัน", rhymeGroup:"y" },

  // B1 - Society & Community
  { id:215, word:"community", phonetic:"/kəˈmjuːnəti/", thai:"ชุมชน", category:"society", level:"B1", rhyme:"ชุม ชน ช่วย กัน สร้าง สังคม ที่ ดี", example:"Help your community.", exampleThai:"ช่วยเหลือชุมชนของคุณ", rhymeGroup:"y" },
  { id:216, word:"culture", phonetic:"/ˈkʌltʃər/", thai:"วัฒนธรรม", category:"society", level:"A2", rhyme:"วัฒน ธรรม งาม งด ควร ภูมิ ใจ", example:"Thai culture is unique.", exampleThai:"วัฒนธรรมไทยมีเอกลักษณ์", rhymeGroup:"er" },
  { id:217, word:"tradition", phonetic:"/trəˈdɪʃn/", thai:"ประเพณี", category:"society", level:"A2", rhyme:"ประเพณี สืบ ทอด จาก รุ่น สู่ รุ่น", example:"Traditions are important.", exampleThai:"ประเพณีมีความสำคัญ", rhymeGroup:"on" },
  { id:218, word:"freedom", phonetic:"/ˈfriːdəm/", thai:"อิสรภาพ", category:"society", level:"B1", rhyme:"อิสรภาพ ค่า ล้ำ ทุก คน ต้อง มี", example:"Freedom is a basic right.", exampleThai:"อิสรภาพเป็นสิทธิ์พื้นฐาน", rhymeGroup:"om" },
  { id:219, word:"education", phonetic:"/ˌedʒuˈkeɪʃn/", thai:"การศึกษา", category:"society", level:"A2", rhyme:"การ ศึกษา คือ กุญแจ สู่ ความ สำเร็จ", example:"Education changes lives.", exampleThai:"การศึกษาเปลี่ยนชีวิต", rhymeGroup:"on" },
  { id:220, word:"government", phonetic:"/ˈɡʌvənmənt/", thai:"รัฐบาล", category:"society", level:"A2", rhyme:"รัฐ บาล ดู แล ประชา ชน ให้ อยู่ ดี", example:"The government helps citizens.", exampleThai:"รัฐบาลช่วยเหลือประชาชน", rhymeGroup:"ent" },

  // B2 - Abstract concepts
  { id:221, word:"success", phonetic:"/səkˈses/", thai:"ความสำเร็จ", category:"values", level:"A2", rhyme:"ความ สำเร็จ มา จาก ความ พยายาม", example:"Success comes from hard work.", exampleThai:"ความสำเร็จมาจากการทำงานหนัก", rhymeGroup:"ess" },
  { id:222, word:"challenge", phonetic:"/ˈtʃælɪndʒ/", thai:"ความท้าทาย", category:"values", level:"B1", rhyme:"ท้า ทาย คือ โอ กาส ที่ ซ่อน อยู่", example:"Every challenge makes you stronger.", exampleThai:"ทุกความท้าทายทำให้คุณแข็งแกร่งขึ้น", rhymeGroup:"enge" },
  { id:223, word:"opportunity", phonetic:"/ˌɒpəˈtjuːnəti/", thai:"โอกาส", category:"values", level:"B1", rhyme:"โอ กาส มา ต้อง รีบ คว้า ไว้ อย่า ช้า", example:"Take every opportunity.", exampleThai:"คว้าทุกโอกาสที่มี", rhymeGroup:"y" },
  { id:224, word:"responsibility", phonetic:"/rɪˌspɒnsəˈbɪləti/", thai:"ความรับผิดชอบ", category:"values", level:"B1", rhyme:"รับ ผิด ชอบ ต่อ ตัว เอง และ ผู้ อื่น", example:"Take responsibility for your actions.", exampleThai:"รับผิดชอบต่อการกระทำของตัวเอง", rhymeGroup:"y" },
  { id:225, word:"respect", phonetic:"/rɪˈspekt/", thai:"ความเคารพ", category:"values", level:"B1", rhyme:"เคารพ ผู้ อื่น ดั่ง ที่ อยาก ได้ รับ", example:"Respect everyone you meet.", exampleThai:"เคารพทุกคนที่พบเจอ", rhymeGroup:"ect" },
  { id:226, word:"courage", phonetic:"/ˈkʌrɪdʒ/", thai:"ความกล้าหาญ", category:"values", level:"B1", rhyme:"กล้า หาญ ก้าว ออก จาก ความ กลัว ได้", example:"Show courage every day.", exampleThai:"แสดงความกล้าหาญทุกวัน", rhymeGroup:"age" },
  { id:227, word:"justice", phonetic:"/ˈdʒʌstɪs/", thai:"ความยุติธรรม", category:"values", level:"B1", rhyme:"ยุติ ธรรม คือ รากฐาน ของ สังคม ดี", example:"Everyone deserves justice.", exampleThai:"ทุกคนสมควรได้รับความยุติธรรม", rhymeGroup:"ice" },
  { id:228, word:"peace", phonetic:"/piːs/", thai:"สันติภาพ", category:"values", level:"B1", rhyme:"สันติ ภาพ ทำ ให้ โลก น่า อยู่ เสมอ", example:"Peace makes the world better.", exampleThai:"สันติภาพทำให้โลกดีขึ้น", rhymeGroup:"eace" },
  { id:229, word:"knowledge", phonetic:"/ˈnɒlɪdʒ/", thai:"ความรู้", category:"values", level:"B1", rhyme:"ความ รู้ คือ พลัง อำนาจ ที่ ยิ่ง ใหญ่", example:"Knowledge is power.", exampleThai:"ความรู้คือพลัง", rhymeGroup:"edge" },
  { id:230, word:"imagination", phonetic:"/ɪˌmædʒɪˈneɪʃn/", thai:"จินตนาการ", category:"values", level:"B1", rhyme:"จินต นา การ พา ฝัน ไป ไกล ไม่มี ขีด จำกัด", example:"Use your imagination!", exampleThai:"ใช้จินตนาการของคุณ!", rhymeGroup:"on" },

  // A1 - More Animals
  { id:231, word:"rabbit", phonetic:"/ˈræbɪt/", thai:"กระต่าย", category:"animals", level:"A1", rhyme:"กระ ต่าย ขน นุ่ม หู ยาว น่า รัก มาก", example:"The rabbit hops quickly.", exampleThai:"กระต่ายกระโดดเร็ว", rhymeGroup:"it" },
  { id:232, word:"lion", phonetic:"/ˈlaɪən/", thai:"สิงโต", category:"animals", level:"A1", rhyme:"สิง โต ราชา แห่ง สัตว์ ป่า ยิ่ง ใหญ่", example:"The lion is the king of animals.", exampleThai:"สิงโตคือราชาแห่งสัตว์", rhymeGroup:"on" },
  { id:233, word:"tiger", phonetic:"/ˈtaɪɡər/", thai:"เสือ", category:"animals", level:"A1", rhyme:"เสือ ลาย พราว ดุ แต่ งาม ตา นัก", example:"Tigers are strong and fast.", exampleThai:"เสือแข็งแรงและเร็ว", rhymeGroup:"er" },
  { id:234, word:"bear", phonetic:"/beər/", thai:"หมี", category:"animals", level:"A1", rhyme:"หมี ขน ปุย อุ้วย อ้วน น่า กอด", example:"Bears sleep in winter.", exampleThai:"หมีนอนหลับในฤดูหนาว", rhymeGroup:"ear" },
  { id:235, word:"wolf", phonetic:"/wʊlf/", thai:"หมาป่า", category:"animals", level:"A2", rhyme:"หมา ป่า หอน ดัง ยาม คืน มืด เย็น", example:"Wolves live in packs.", exampleThai:"หมาป่าอยู่เป็นฝูง", rhymeGroup:"olf" },
  { id:236, word:"fox", phonetic:"/fɒks/", thai:"สุนัขจิ้งจอก", category:"animals", level:"A2", rhyme:"จิ้ง จอก ฉลาด แสน กลิ้ง กล่อม เก่ง", example:"The fox is clever.", exampleThai:"สุนัขจิ้งจอกฉลาดมาก", rhymeGroup:"ox" },
  { id:237, word:"duck", phonetic:"/dʌk/", thai:"เป็ด", category:"animals", level:"A1", rhyme:"เป็ด ว่าย น้ำ กา กา เพลิน ใจ", example:"Ducks swim on the lake.", exampleThai:"เป็ดว่ายน้ำในทะเลสาบ", rhymeGroup:"uck" },
  { id:238, word:"frog", phonetic:"/frɒɡ/", thai:"กบ", category:"animals", level:"A1", rhyme:"กบ กระโดด ไป มา ริม น้ำ เย็น", example:"Frogs jump very high.", exampleThai:"กบกระโดดสูงมาก", rhymeGroup:"og" },
  { id:239, word:"butterfly", phonetic:"/ˈbʌtəflaɪ/", thai:"ผีเสื้อ", category:"animals", level:"A1", rhyme:"ผี เสื้อ บิน สวย งาม สี สด ใส", example:"The butterfly has colorful wings.", exampleThai:"ผีเสื้อมีปีกสีสวย", rhymeGroup:"y" },
  { id:240, word:"bee", phonetic:"/biː/", thai:"ผึ้ง", category:"animals", level:"A1", rhyme:"ผึ้ง บิน ว่อน เก็บ น้ำ หวาน หอม ฉุน", example:"Bees make honey.", exampleThai:"ผึ้งทำน้ำผึ้ง", rhymeGroup:"ee" },
  { id:241, word:"snake", phonetic:"/sneɪk/", thai:"งู", category:"animals", level:"A1", rhyme:"งู เลื้อย คดเคี้ยว ไป ใน ป่า เงียบ", example:"Some snakes are dangerous.", exampleThai:"งูบางชนิดอันตราย", rhymeGroup:"ake" },
  { id:242, word:"spider", phonetic:"/ˈspaɪdər/", thai:"แมงมุม", category:"animals", level:"A1", rhyme:"แมง มุม ชัก ใย ดัก แมลง แสน เก่ง", example:"Spiders spin webs.", exampleThai:"แมงมุมชักใย", rhymeGroup:"er" },
  { id:243, word:"whale", phonetic:"/weɪl/", thai:"วาฬ", category:"animals", level:"A2", rhyme:"วาฬ ใหญ่ ยักษ์ แห่ง ท้อง ทะเล ลึก", example:"Whales are the biggest animals.", exampleThai:"วาฬเป็นสัตว์ที่ใหญ่ที่สุด", rhymeGroup:"ale" },
  { id:244, word:"dolphin", phonetic:"/ˈdɒlfɪn/", thai:"โลมา", category:"animals", level:"A2", rhyme:"โลมา ฉลาด ว่าย น้ำ สนุก สบาย", example:"Dolphins are very intelligent.", exampleThai:"โลมาฉลาดมาก", rhymeGroup:"in" },
  { id:245, word:"penguin", phonetic:"/ˈpeŋɡwɪn/", thai:"เพนกวิน", category:"animals", level:"A1", rhyme:"เพน กวิน เดิน ตุ๊บ ป่อง น่า รัก มาก", example:"Penguins live in cold places.", exampleThai:"เพนกวินอาศัยอยู่ในที่หนาว", rhymeGroup:"in" },

  // A1 - More Colors
  { id:246, word:"purple", phonetic:"/ˈpɜːpl/", thai:"สีม่วง", category:"colors", level:"A1", rhyme:"ม่วง งาม ดั่ง ดอก ลาเวน เดอร์ หอม", example:"Purple is a royal color.", exampleThai:"สีม่วงเป็นสีของราชวงศ์", rhymeGroup:"le" },
  { id:247, word:"brown", phonetic:"/braʊn/", thai:"สีน้ำตาล", category:"colors", level:"A1", rhyme:"น้ำ ตาล ดิน ชื้น ต้นไม้ งอก งาม", example:"Tree trunks are brown.", exampleThai:"ลำต้นไม้สีน้ำตาล", rhymeGroup:"own" },
  { id:248, word:"grey", phonetic:"/ɡreɪ/", thai:"สีเทา", category:"colors", level:"A1", rhyme:"เทา เมฆ ครึ้ม ฟ้า ก่อน ฝน ตก", example:"Elephants are grey.", exampleThai:"ช้างสีเทา", rhymeGroup:"ey" },
  { id:249, word:"gold", phonetic:"/ɡoʊld/", thai:"สีทอง", category:"colors", level:"A2", rhyme:"ทอง ส่อง แสง แวว วาว งาม ตา", example:"Gold is a precious color.", exampleThai:"ทองเป็นสีที่มีค่า", rhymeGroup:"old" },
  { id:250, word:"silver", phonetic:"/ˈsɪlvər/", thai:"สีเงิน", category:"colors", level:"A2", rhyme:"เงิน วาว พราว สวย งาม ดั่ง ดาว", example:"Silver shines like the moon.", exampleThai:"สีเงินแวววาวเหมือนดวงจันทร์", rhymeGroup:"er" },

  // A1 - More Food
  { id:251, word:"potato", phonetic:"/pəˈteɪtoʊ/", thai:"มันฝรั่ง", category:"food", level:"A1", rhyme:"มัน ฝรั่ง อบ กรอบ หอม กลิ่น ชวน กิน", example:"I like potato chips.", exampleThai:"ฉันชอบมันฝรั่งทอด", rhymeGroup:"o" },
  { id:252, word:"tomato", phonetic:"/təˈmɑːtoʊ/", thai:"มะเขือเทศ", category:"food", level:"A1", rhyme:"มะ เขือ เทศ แดง ฉ่ำ รส เปรี้ยว หวาน", example:"Tomatoes are red and juicy.", exampleThai:"มะเขือเทศสีแดงและฉ่ำ", rhymeGroup:"o" },
  { id:253, word:"carrot", phonetic:"/ˈkærət/", thai:"แครอท", category:"food", level:"A1", rhyme:"แค รอท ส้ม สด กรอบ ดี ต่อ สายตา", example:"Rabbits love carrots.", exampleThai:"กระต่ายชอบแครอท", rhymeGroup:"ot" },
  { id:254, word:"onion", phonetic:"/ˈʌnjən/", thai:"หัวหอม", category:"food", level:"A1", rhyme:"หัว หอม กลิ่น ฉุน ทำ น้ำตา ไหล พลัน", example:"Onions make you cry.", exampleThai:"หัวหอมทำให้น้ำตาไหล", rhymeGroup:"on" },
  { id:255, word:"cheese", phonetic:"/tʃiːz/", thai:"เนยแข็ง", category:"food", level:"A1", rhyme:"เนย แข็ง หอม มัน รส ชาติ เข้ม ข้น", example:"I love cheese on pizza.", exampleThai:"ฉันชอบชีสบนพิซซ่า", rhymeGroup:"eese" },
  { id:256, word:"butter", phonetic:"/ˈbʌtər/", thai:"เนย", category:"food", level:"A1", rhyme:"เนย นุ่ม ทา ขนมปัง หอม อร่อย นัก", example:"Spread butter on the bread.", exampleThai:"ทาเนยบนขนมปัง", rhymeGroup:"er" },
  { id:257, word:"sandwich", phonetic:"/ˈsænwɪtʃ/", thai:"แซนวิช", category:"food", level:"A1", rhyme:"แซน วิช อร่อย พกพา สะดวก ง่าย", example:"I eat a sandwich for lunch.", exampleThai:"ฉันกินแซนวิชตอนเที่ยง", rhymeGroup:"ich" },
  { id:258, word:"salad", phonetic:"/ˈsæləd/", thai:"สลัด", category:"food", level:"A1", rhyme:"สลัด สด ใหม่ ผัก หลาก สี สวย งาม", example:"A salad is healthy.", exampleThai:"สลัดดีต่อสุขภาพ", rhymeGroup:"ad" },
  { id:259, word:"pizza", phonetic:"/ˈpiːtsə/", thai:"พิซซ่า", category:"food", level:"A1", rhyme:"พิซ ซ่า กลม กรอบ หอม ชีส ละลาย", example:"Pizza is my favourite food.", exampleThai:"พิซซ่าคืออาหารโปรดของฉัน", rhymeGroup:"a" },
  { id:260, word:"noodle", phonetic:"/ˈnuːdl/", thai:"บะหมี่/เส้น", category:"food", level:"A1", rhyme:"บะ หมี่ เส้น นุ่ม ซด ร้อน อร่อย นัก", example:"I love noodle soup.", exampleThai:"ฉันชอบก๋วยเตี๋ยว", rhymeGroup:"le" },
  { id:261, word:"pepper", phonetic:"/ˈpepər/", thai:"พริก/พริกไทย", category:"food", level:"A1", rhyme:"พริก เผ็ด ร้อน ลิ้น ชา ซ่า เต็ม ปาก", example:"Add pepper for spice.", exampleThai:"ใส่พริกเพื่อความเผ็ด", rhymeGroup:"er" },
  { id:262, word:"lemon", phonetic:"/ˈlemən/", thai:"มะนาว", category:"food", level:"A1", rhyme:"มะ นาว เปรี้ยว สด ชื่น ดื่ม แล้ว สดชื่น", example:"Lemon is sour but healthy.", exampleThai:"มะนาวเปรี้ยวแต่ดีต่อสุขภาพ", rhymeGroup:"on" },
  { id:263, word:"honey", phonetic:"/ˈhʌni/", thai:"น้ำผึ้ง", category:"food", level:"A1", rhyme:"น้ำ ผึ้ง หวาน ชื่น คอ แสน อร่อย", example:"Honey is sweet and natural.", exampleThai:"น้ำผึ้งหวานและเป็นธรรมชาติ", rhymeGroup:"y" },

  // A1 - More Body Parts
  { id:264, word:"finger", phonetic:"/ˈfɪŋɡər/", thai:"นิ้ว", category:"body", level:"A1", rhyme:"นิ้ว สิบ นิ้ว ทำ งาน สร้าง สิ่ง ดี", example:"Count on your fingers.", exampleThai:"นับด้วยนิ้วมือ", rhymeGroup:"er" },
  { id:265, word:"tooth", phonetic:"/tuːθ/", thai:"ฟัน", category:"body", level:"A1", rhyme:"ฟัน ขาว สะอาด แปรง ทุก วัน ดี", example:"Brush your teeth twice a day.", exampleThai:"แปรงฟันวันละสองครั้ง", rhymeGroup:"ooth" },
  { id:266, word:"hair", phonetic:"/heər/", thai:"ผม", category:"body", level:"A1", rhyme:"ผม งาม สวย หวี ทุก เช้า สดใส", example:"She has long black hair.", exampleThai:"เธอมีผมยาวสีดำ", rhymeGroup:"air" },
  { id:267, word:"knee", phonetic:"/niː/", thai:"เข่า", category:"body", level:"A1", rhyme:"เข่า งอ ก้าว เดิน ไป ข้าง หน้า ดี", example:"Bend your knees when you jump.", exampleThai:"งอเข่าตอนกระโดด", rhymeGroup:"ee" },
  { id:268, word:"shoulder", phonetic:"/ˈʃoʊldər/", thai:"ไหล่", category:"body", level:"A1", rhyme:"ไหล่ กว้าง แบก ภาร กิจ ได้ ไม่ หวั่น", example:"Pat your friend on the shoulder.", exampleThai:"ตบไหล่เพื่อน", rhymeGroup:"er" },
  { id:269, word:"stomach", phonetic:"/ˈstʌmək/", thai:"กระเพาะ/ท้อง", category:"body", level:"A1", rhyme:"ท้อง ร้อง หิว ต้อง กิน ข้าว เร็ว ๆ", example:"My stomach is hungry.", exampleThai:"ท้องของฉันหิว", rhymeGroup:"ach" },
  { id:270, word:"throat", phonetic:"/θroʊt/", thai:"คอ", category:"body", level:"A2", rhyme:"คอ ใส ร้อง เพลง หวาน ไพเราะ ชื่น", example:"Drink water for your throat.", exampleThai:"ดื่มน้ำเพื่อคอ", rhymeGroup:"oat" },

  // A1 - More School/Study
  { id:271, word:"pencil", phonetic:"/ˈpensl/", thai:"ดินสอ", category:"school", level:"A1", rhyme:"ดิน สอ เขียน แล้ว ลบ ได้ ไม่ เป็น ไร", example:"Draw with a pencil.", exampleThai:"วาดด้วยดินสอ", rhymeGroup:"il" },
  { id:272, word:"paper", phonetic:"/ˈpeɪpər/", thai:"กระดาษ", category:"school", level:"A1", rhyme:"กระดาษ ขาว เขียน ฝัน ลง ไว้ ทุก ใบ", example:"Write on paper.", exampleThai:"เขียนบนกระดาษ", rhymeGroup:"er" },
  { id:273, word:"homework", phonetic:"/ˈhoʊmwɜːk/", thai:"การบ้าน", category:"school", level:"A1", rhyme:"การ บ้าน ทำ ก่อน นอน แล้ว ฝัน ดี", example:"Do your homework first.", exampleThai:"ทำการบ้านก่อนนะ", rhymeGroup:"ork" },
  { id:274, word:"exam", phonetic:"/ɪɡˈzæm/", thai:"การสอบ", category:"school", level:"A1", rhyme:"สอบ ตั้ง ใจ อ่าน หนังสือ ผ่าน ได้ แน่", example:"Study hard for the exam.", exampleThai:"ตั้งใจอ่านหนังสือเพื่อสอบ", rhymeGroup:"am" },
  { id:275, word:"question", phonetic:"/ˈkwestʃən/", thai:"คำถาม", category:"school", level:"A1", rhyme:"คำ ถาม ดี ทำ ให้ รู้ มาก ขึ้น", example:"Ask questions in class.", exampleThai:"ถามคำถามในชั้นเรียน", rhymeGroup:"on" },
  { id:276, word:"mistake", phonetic:"/mɪˈsteɪk/", thai:"ข้อผิดพลาด", category:"school", level:"A2", rhyme:"ผิด พลาด แล้ว แก้ ไข ดี กว่า เดิม", example:"Learn from your mistakes.", exampleThai:"เรียนรู้จากข้อผิดพลาด", rhymeGroup:"ake" },
  { id:277, word:"dictionary", phonetic:"/ˈdɪkʃəneri/", thai:"พจนานุกรม", category:"school", level:"A1", rhyme:"พจนา นุกรม ค้น หา คำ ศัพท์ ได้ ทุก คำ", example:"Use a dictionary to learn words.", exampleThai:"ใช้พจนานุกรมเรียนคำศัพท์", rhymeGroup:"y" },
  { id:278, word:"science", phonetic:"/ˈsaɪəns/", thai:"วิทยาศาสตร์", category:"school", level:"A1", rhyme:"วิทยา ศาสตร์ ค้น หา ความ จริง ของ โลก", example:"Science explains the world.", exampleThai:"วิทยาศาสตร์อธิบายโลก", rhymeGroup:"ence" },
  { id:279, word:"history", phonetic:"/ˈhɪstri/", thai:"ประวัติศาสตร์", category:"school", level:"A1", rhyme:"ประวัติ ศาสตร์ บอก เล่า เรื่อง ราว ใน อดีต", example:"History teaches us lessons.", exampleThai:"ประวัติศาสตร์สอนบทเรียนแก่เรา", rhymeGroup:"y" },
  { id:280, word:"mathematics", phonetic:"/ˌmæθəˈmætɪks/", thai:"คณิตศาสตร์", category:"school", level:"A1", rhyme:"คณิต ศาสตร์ นับ คิด คำนวณ ได้ แม่นยำ", example:"Mathematics is fun!", exampleThai:"คณิตศาสตร์สนุก!", rhymeGroup:"ics" },

  // A1 - More Home
  { id:281, word:"room", phonetic:"/ruːm/", thai:"ห้อง", category:"home", level:"A1", rhyme:"ห้อง สะอาด จัด ระเบียบ ดี น่า อยู่", example:"Clean your room every day.", exampleThai:"ทำความสะอาดห้องทุกวัน", rhymeGroup:"oom" },
  { id:282, word:"floor", phonetic:"/flɔːr/", thai:"พื้น", category:"home", level:"A1", rhyme:"พื้น สะอาด เดิน ไป ไม่ ลื่น หกล้ม", example:"Sweep the floor clean.", exampleThai:"กวาดพื้นให้สะอาด", rhymeGroup:"oor" },
  { id:283, word:"wall", phonetic:"/wɔːl/", thai:"ผนัง", category:"home", level:"A1", rhyme:"ผนัง ห้อง แขวน ภาพ งาม สวย ตา", example:"Hang a picture on the wall.", exampleThai:"แขวนรูปบนผนัง", rhymeGroup:"all" },
  { id:284, word:"roof", phonetic:"/ruːf/", thai:"หลังคา", category:"home", level:"A1", rhyme:"หลัง คา กัน ฝน กัน แดด ให้ อบอุ่น", example:"The roof keeps us dry.", exampleThai:"หลังคากันฝนให้เรา", rhymeGroup:"oof" },
  { id:285, word:"bathroom", phonetic:"/ˈbɑːθruːm/", thai:"ห้องน้ำ", category:"home", level:"A1", rhyme:"ห้อง น้ำ สะอาด อาบ น้ำ ทุก วัน ดี", example:"Wash your hands in the bathroom.", exampleThai:"ล้างมือในห้องน้ำ", rhymeGroup:"oom" },
  { id:286, word:"sofa", phonetic:"/ˈsoʊfə/", thai:"โซฟา", category:"home", level:"A1", rhyme:"โซ ฟา นุ่ม นั่ง เล่น พัก ผ่อน สบาย", example:"Sit on the sofa and relax.", exampleThai:"นั่งบนโซฟาพักผ่อน", rhymeGroup:"a" },
  { id:287, word:"lamp", phonetic:"/læmp/", thai:"โคมไฟ", category:"home", level:"A1", rhyme:"โคม ไฟ ส่อง แสง สว่าง ยาม กลาง คืน", example:"Turn on the lamp.", exampleThai:"เปิดโคมไฟ", rhymeGroup:"amp" },
  { id:288, word:"fridge", phonetic:"/frɪdʒ/", thai:"ตู้เย็น", category:"home", level:"A1", rhyme:"ตู้ เย็น เก็บ อาหาร สด ไว้ กิน นาน", example:"Keep food in the fridge.", exampleThai:"เก็บอาหารในตู้เย็น", rhymeGroup:"idge" },
  { id:289, word:"clock", phonetic:"/klɒk/", thai:"นาฬิกา", category:"home", level:"A1", rhyme:"นา ฬิ กา บอก เวลา ไม่ หยุด เดิน", example:"The clock says it's noon.", exampleThai:"นาฬิกาบอกว่าเที่ยงแล้ว", rhymeGroup:"ock" },
  { id:290, word:"mirror", phonetic:"/ˈmɪrər/", thai:"กระจก", category:"home", level:"A1", rhyme:"กระ จก ส่อง หน้า ยิ้ม ให้ ตัว เอง", example:"Look in the mirror.", exampleThai:"ส่องกระจก", rhymeGroup:"or" },

  // A2 - Weather
  { id:291, word:"weather", phonetic:"/ˈweðər/", thai:"อากาศ", category:"weather", level:"A1", rhyme:"อากาศ ดี ออก ไป เดิน เล่น สบาย ใจ", example:"What's the weather like today?", exampleThai:"วันนี้อากาศเป็นยังไง?", rhymeGroup:"er" },
  { id:292, word:"storm", phonetic:"/stɔːm/", thai:"พายุ", category:"weather", level:"A2", rhyme:"พายุ พัด แรง แต่ หลัง พายุ ฟ้า ใส", example:"The storm passed quickly.", exampleThai:"พายุผ่านไปเร็ว", rhymeGroup:"orm" },
  { id:293, word:"thunder", phonetic:"/ˈθʌndər/", thai:"ฟ้าร้อง", category:"weather", level:"A2", rhyme:"ฟ้า ร้อง ดัง กึก ก้อง แต่ ไม่ ต้อง กลัว", example:"Thunder is very loud.", exampleThai:"ฟ้าร้องดังมาก", rhymeGroup:"er" },
  { id:294, word:"lightning", phonetic:"/ˈlaɪtnɪŋ/", thai:"ฟ้าแลบ", category:"weather", level:"A2", rhyme:"ฟ้า แลบ วาบ สว่าง เร็ว ดั่ง สาย ฟ้า", example:"Lightning lit up the sky.", exampleThai:"ฟ้าแลบสว่างท้องฟ้า", rhymeGroup:"ing" },
  { id:295, word:"foggy", phonetic:"/ˈfɒɡi/", thai:"มีหมอก", category:"weather", level:"A2", rhyme:"หมอก ลง จัด มอง ไม่ เห็น ทาง ไกล", example:"It's foggy this morning.", exampleThai:"เช้านี้มีหมอก", rhymeGroup:"y" },
  { id:296, word:"sunny", phonetic:"/ˈsʌni/", thai:"แดดออก", category:"weather", level:"A1", rhyme:"แดด ออก จ้า ฟ้า ใส วัน ดี งาม", example:"It's a sunny day!", exampleThai:"วันนี้แดดออกสวย!", rhymeGroup:"y" },
  { id:297, word:"windy", phonetic:"/ˈwɪndi/", thai:"มีลมแรง", category:"weather", level:"A1", rhyme:"ลม แรง พัด พลิ้ว ผม สดชื่น ดี นัก", example:"It's very windy outside.", exampleThai:"ข้างนอกลมแรงมาก", rhymeGroup:"y" },
  { id:298, word:"snowy", phonetic:"/ˈsnoʊi/", thai:"มีหิมะ", category:"weather", level:"A1", rhyme:"หิมะ ตก ขาว โพลน สวย งาม ราว ฝัน", example:"It's snowy in winter.", exampleThai:"ฤดูหนาวมีหิมะ", rhymeGroup:"y" },

  // A2 - Transport extras
  { id:299, word:"taxi", phonetic:"/ˈtæksi/", thai:"แท็กซี่", category:"transport", level:"A1", rhyme:"แท็ก ซี่ รับ ส่ง ถึง ที่ หมาย สะดวก", example:"Take a taxi to the airport.", exampleThai:"นั่งแท็กซี่ไปสนามบิน", rhymeGroup:"y" },
  { id:300, word:"motorcycle", phonetic:"/ˈmoʊtəsaɪkl/", thai:"มอเตอร์ไซค์", category:"transport", level:"A1", rhyme:"มอเตอร์ไซค์ ซิ่ง เร็ว ลัด ตรอก ซอก ซอย", example:"He rides a motorcycle.", exampleThai:"เขาขี่มอเตอร์ไซค์", rhymeGroup:"le" },
  { id:301, word:"helicopter", phonetic:"/ˈhelɪkɒptər/", thai:"เฮลิคอปเตอร์", category:"transport", level:"A2", rhyme:"เฮลิ คอป เตอร์ บิน หมุน ใบ พัด สูง ลิบ", example:"The helicopter flew over us.", exampleThai:"เฮลิคอปเตอร์บินผ่านเหนือเรา", rhymeGroup:"er" },
  { id:302, word:"ship", phonetic:"/ʃɪp/", thai:"เรือใหญ่", category:"transport", level:"A2", rhyme:"เรือ ใหญ่ แล่น ข้าม ทะเล กว้าง ไกล", example:"The ship crosses the ocean.", exampleThai:"เรือข้ามมหาสมุทร", rhymeGroup:"ip" },
  { id:303, word:"truck", phonetic:"/trʌk/", thai:"รถบรรทุก", category:"transport", level:"A1", rhyme:"รถ บรรทุก ขน สินค้า ไป ทั่ว ไทย", example:"The truck carries heavy goods.", exampleThai:"รถบรรทุกขนสินค้าหนัก", rhymeGroup:"uck" },

  // A2 - More Actions
  { id:304, word:"talk", phonetic:"/tɔːk/", thai:"พูดคุย", category:"actions", level:"A1", rhyme:"พูด คุย สื่อ สาร ด้วย ใจ ที่ ดี", example:"Talk to your friends.", exampleThai:"พูดคุยกับเพื่อนๆ", rhymeGroup:"alk" },
  { id:305, word:"listen", phonetic:"/ˈlɪsn/", thai:"ฟัง", category:"actions", level:"A1", rhyme:"ฟัง ด้วย ใจ จด จ่อ เข้าใจ มาก ขึ้น", example:"Listen carefully to the teacher.", exampleThai:"ฟังครูอย่างตั้งใจ", rhymeGroup:"en" },
  { id:306, word:"walk", phonetic:"/wɔːk/", thai:"เดิน", category:"actions", level:"A1", rhyme:"เดิน ก้าว ละ ก้าว ไป ถึง ฝัน แน่", example:"Walk in the park every day.", exampleThai:"เดินในสวนทุกวัน", rhymeGroup:"alk" },
  { id:307, word:"climb", phonetic:"/klaɪm/", thai:"ปีน", category:"actions", level:"A1", rhyme:"ปีน ป่าย สูง ขึ้น ไป ถึง จุด สูงสุด", example:"Climb the mountain slowly.", exampleThai:"ปีนเขาอย่างช้าๆ", rhymeGroup:"ime" },
  { id:308, word:"throw", phonetic:"/θroʊ/", thai:"โยน", category:"actions", level:"A1", rhyme:"โยน ลูก บอล ไป ไกล ดั่ง ฝัน", example:"Throw the ball to your friend.", exampleThai:"โยนบอลให้เพื่อน", rhymeGroup:"ow" },
  { id:309, word:"catch", phonetic:"/kætʃ/", thai:"รับ/จับ", category:"actions", level:"A1", rhyme:"รับ ลูก บอล ด้วย มือ ทั้ง สอง ดี", example:"Catch the ball!", exampleThai:"รับบอล!", rhymeGroup:"atch" },
  { id:310, word:"push", phonetic:"/pʊʃ/", thai:"ดัน", category:"actions", level:"A1", rhyme:"ดัน ไป ข้าง หน้า อย่า หยุด ไม่ ถอย", example:"Push the door open.", exampleThai:"ดันประตูให้เปิด", rhymeGroup:"ush" },
  { id:311, word:"pull", phonetic:"/pʊl/", thai:"ดึง", category:"actions", level:"A1", rhyme:"ดึง ดูด ใจ ให้ อยาก ทำ ต่อ ไป", example:"Pull the rope hard.", exampleThai:"ดึงเชือกแรงๆ", rhymeGroup:"ul" },
  { id:312, word:"cook", phonetic:"/kʊk/", thai:"ทำอาหาร", category:"actions", level:"A1", rhyme:"ทำ อาหาร อร่อย ด้วย ใจ ที่ รัก", example:"Cook dinner for the family.", exampleThai:"ทำอาหารเย็นให้ครอบครัว", rhymeGroup:"ook" },
  { id:313, word:"draw", phonetic:"/drɔː/", thai:"วาดรูป", category:"actions", level:"A1", rhyme:"วาด รูป ฝัน สวย งาม ลง ผืน ผ้า", example:"Draw a picture of your family.", exampleThai:"วาดรูปครอบครัวของคุณ", rhymeGroup:"aw" },
  { id:314, word:"build", phonetic:"/bɪld/", thai:"สร้าง", category:"actions", level:"A1", rhyme:"สร้าง สิ่ง ดี ขึ้น มา ด้วย มือ ตัว เอง", example:"Build a sandcastle on the beach.", exampleThai:"สร้างปราสาททรายที่ชายหาด", rhymeGroup:"ild" },
  { id:315, word:"open", phonetic:"/ˈoʊpən/", thai:"เปิด", category:"actions", level:"A1", rhyme:"เปิด ใจ รับ สิ่ง ใหม่ ชีวิต ดี ขึ้น", example:"Open the window for fresh air.", exampleThai:"เปิดหน้าต่างรับอากาศบริสุทธิ์", rhymeGroup:"en" },
  { id:316, word:"close", phonetic:"/kloʊz/", thai:"ปิด", category:"actions", level:"A1", rhyme:"ปิด ประตู แล้ว พัก ผ่อน อย่าง เต็ม ที่", example:"Close the door, please.", exampleThai:"ช่วยปิดประตูด้วยนะ", rhymeGroup:"ose" },
  { id:317, word:"wait", phonetic:"/weɪt/", thai:"รอ", category:"actions", level:"A1", rhyme:"รอ ด้วย ใจ เย็น ผล ดี จะ มา เอง", example:"Wait for the bus here.", exampleThai:"รอรถบัสตรงนี้", rhymeGroup:"ait" },
  { id:318, word:"choose", phonetic:"/tʃuːz/", thai:"เลือก", category:"actions", level:"A2", rhyme:"เลือก สิ่ง ที่ ดี ที่สุด เพื่อ ชีวิต", example:"Choose wisely every day.", exampleThai:"เลือกอย่างฉลาดทุกวัน", rhymeGroup:"oose" },
  { id:319, word:"explain", phonetic:"/ɪkˈspleɪn/", thai:"อธิบาย", category:"actions", level:"A2", rhyme:"อธิ บาย ชัด เจน ให้ เข้า ใจ ได้ ดี", example:"Explain your answer clearly.", exampleThai:"อธิบายคำตอบอย่างชัดเจน", rhymeGroup:"ain" },
  { id:320, word:"celebrate", phonetic:"/ˈselɪbreɪt/", thai:"ฉลอง", category:"actions", level:"A2", rhyme:"ฉลอง ความ สำเร็จ ด้วย ใจ ยินดี", example:"Celebrate your birthday!", exampleThai:"ฉลองวันเกิดด้วย!", rhymeGroup:"ate" },

  // A2 - More Adjectives
  { id:321, word:"tired", phonetic:"/ˈtaɪəd/", thai:"เหนื่อย", category:"adjectives", level:"A1", rhyme:"เหนื่อย แล้ว นอน พัก แล้ว ลุก ขึ้น ใหม่", example:"I'm tired after the long walk.", exampleThai:"ฉันเหนื่อยหลังเดินไกล", rhymeGroup:"ired" },
  { id:322, word:"wonderful", phonetic:"/ˈwʌndəfl/", thai:"วิเศษ/ยอดเยี่ยม", category:"adjectives", level:"A1", rhyme:"วิ เศษ ยอด เยี่ยม ดี ที่สุด ใน โลก", example:"What a wonderful day!", exampleThai:"วันที่วิเศษมากเลย!", rhymeGroup:"ul" },
  { id:323, word:"delicious", phonetic:"/dɪˈlɪʃəs/", thai:"อร่อย", category:"adjectives", level:"A1", rhyme:"อร่อย มาก กิน แล้ว ยิ้ม ไม่ หุบ", example:"This food is delicious!", exampleThai:"อาหารนี้อร่อยมาก!", rhymeGroup:"ous" },
  { id:324, word:"difficult", phonetic:"/ˈdɪfɪkəlt/", thai:"ยาก", category:"adjectives", level:"A1", rhyme:"ยาก แต่ ถ้า ตั้ง ใจ ก็ ทำ ได้", example:"This question is difficult.", exampleThai:"คำถามนี้ยากมาก", rhymeGroup:"ult" },
  { id:325, word:"easy", phonetic:"/ˈiːzi/", thai:"ง่าย", category:"adjectives", level:"A1", rhyme:"ง่าย นิด เดียว ลอง ดู แล้ว จะ รู้ เอง", example:"This game is easy!", exampleThai:"เกมนี้ง่ายมาก!", rhymeGroup:"y" },
  { id:326, word:"safe", phonetic:"/seɪf/", thai:"ปลอดภัย", category:"adjectives", level:"A1", rhyme:"ปลอด ภัย ดี กว่า ระวัง ตัว เสมอ", example:"Keep safe on the road.", exampleThai:"ระวังตัวบนถนน", rhymeGroup:"afe" },
  { id:327, word:"dangerous", phonetic:"/ˈdeɪndʒərəs/", thai:"อันตราย", category:"adjectives", level:"A1", rhyme:"อันตราย ต้อง ระวัง ให้ ดี ทุก เมื่อ", example:"Be careful, it's dangerous.", exampleThai:"ระวังด้วย มันอันตราย", rhymeGroup:"ous" },
  { id:328, word:"famous", phonetic:"/ˈfeɪməs/", thai:"มีชื่อเสียง", category:"adjectives", level:"A1", rhyme:"มี ชื่อ เสียง แต่ ต้อง ไม่ ลืม ตัว", example:"She is a famous singer.", exampleThai:"เธอเป็นนักร้องมีชื่อเสียง", rhymeGroup:"ous" },
  { id:329, word:"modern", phonetic:"/ˈmɒdn/", thai:"ทันสมัย", category:"adjectives", level:"A2", rhyme:"ทัน สมัย เปลี่ยน ไป ตาม โลก ที่ หมุน", example:"The city looks very modern.", exampleThai:"เมืองดูทันสมัยมาก", rhymeGroup:"ern" },
  { id:330, word:"ancient", phonetic:"/ˈeɪnʃənt/", thai:"โบราณ", category:"adjectives", level:"A2", rhyme:"โบราณ เก่า แก่ มี คุณ ค่า ล้ำ เลิศ", example:"The ancient temple is beautiful.", exampleThai:"วัดโบราณสวยงามมาก", rhymeGroup:"ent" },
  { id:331, word:"popular", phonetic:"/ˈpɒpjələr/", thai:"เป็นที่นิยม", category:"adjectives", level:"A1", rhyme:"นิยม ทั่ว ไป ทุก คน ต่าง ชื่น ชอบ", example:"This song is very popular.", exampleThai:"เพลงนี้เป็นที่นิยมมาก", rhymeGroup:"ar" },
  { id:332, word:"polite", phonetic:"/pəˈlaɪt/", thai:"สุภาพ", category:"adjectives", level:"A2", rhyme:"สุภาพ อ่อน โยน ทุก คน รัก ใคร", example:"Always be polite.", exampleThai:"จงสุภาพเสมอ", rhymeGroup:"ite" },
  { id:333, word:"useful", phonetic:"/ˈjuːsfl/", thai:"มีประโยชน์", category:"adjectives", level:"A1", rhyme:"มี ประ โยชน์ ทำ ให้ โลก ดี ขึ้น", example:"A dictionary is very useful.", exampleThai:"พจนานุกรมมีประโยชน์มาก", rhymeGroup:"ul" },
  { id:334, word:"interesting", phonetic:"/ˈɪntrəstɪŋ/", thai:"น่าสนใจ", category:"adjectives", level:"A1", rhyme:"น่า สนใจ ทำ ให้ อยาก รู้ อยาก เห็น", example:"This book is very interesting.", exampleThai:"หนังสือเล่มนี้น่าสนใจมาก", rhymeGroup:"ing" },

  // B1 - Travel
  { id:335, word:"travel", phonetic:"/ˈtrævl/", thai:"เดินทาง", category:"travel", level:"A1", rhyme:"เดิน ทาง ไกล เปิด โลก ทัศน์ ใหม่ ๆ", example:"I love to travel the world.", exampleThai:"ฉันชอบเดินทางรอบโลก", rhymeGroup:"el" },
  { id:336, word:"passport", phonetic:"/ˈpɑːspɔːt/", thai:"หนังสือเดินทาง", category:"travel", level:"A1", rhyme:"หนังสือ เดิน ทาง พา ฝัน ออก ไป ทั่ว โลก", example:"Don't forget your passport.", exampleThai:"อย่าลืมหนังสือเดินทาง", rhymeGroup:"ort" },
  { id:337, word:"ticket", phonetic:"/ˈtɪkɪt/", thai:"ตั๋ว", category:"travel", level:"A1", rhyme:"ตั๋ว ใบ เล็ก พา ฝัน ไป ถึง จุด หมาย", example:"Buy a ticket for the train.", exampleThai:"ซื้อตั๋วรถไฟ", rhymeGroup:"et" },
  { id:338, word:"luggage", phonetic:"/ˈlʌɡɪdʒ/", thai:"กระเป๋าเดินทาง", category:"travel", level:"A2", rhyme:"กระเป๋า เดิน ทาง บรรจุ ความ ทรง จำ ดี", example:"Pack your luggage the night before.", exampleThai:"แพ็คกระเป๋าก่อนคืน", rhymeGroup:"age" },
  { id:339, word:"map", phonetic:"/mæp/", thai:"แผนที่", category:"travel", level:"A1", rhyme:"แผน ที่ พา ทาง ไม่ หลง ถึง จุด หมาย", example:"Use a map to find the way.", exampleThai:"ใช้แผนที่หาทาง", rhymeGroup:"ap" },
  { id:340, word:"tour", phonetic:"/tʊər/", thai:"ทัวร์/ท่องเที่ยว", category:"travel", level:"A2", rhyme:"ทัวร์ ท่อง เที่ยว เปิด โลก ประสบ การณ์ ดี", example:"Join a tour to see the city.", exampleThai:"ร่วมทัวร์ชมเมือง", rhymeGroup:"our" },
  { id:341, word:"journey", phonetic:"/ˈdʒɜːni/", thai:"การเดินทาง", category:"travel", level:"A2", rhyme:"การ เดิน ทาง คือ บทเรียน ชีวิต", example:"Life is a long journey.", exampleThai:"ชีวิตคือการเดินทางที่ยาวไกล", rhymeGroup:"y" },
  { id:342, word:"adventure", phonetic:"/ədˈventʃər/", thai:"การผจญภัย", category:"travel", level:"A2", rhyme:"ผจญ ภัย ตื่น เต้น เปิด โลก ใหม่ ทุก วัน", example:"Every trip is an adventure.", exampleThai:"ทุกการเดินทางคือการผจญภัย", rhymeGroup:"er" },

  // B1 - Communication
  { id:343, word:"language", phonetic:"/ˈlæŋɡwɪdʒ/", thai:"ภาษา", category:"communication", level:"A1", rhyme:"ภาษา เชื่อม ใจ คน ทั่ว โลก เข้า หา กัน", example:"Learn a new language.", exampleThai:"เรียนภาษาใหม่", rhymeGroup:"age" },
  { id:344, word:"message", phonetic:"/ˈmesɪdʒ/", thai:"ข้อความ", category:"communication", level:"A1", rhyme:"ข้อ ความ ส่ง ไป บอก รัก ได้ ทุก วัน", example:"Send a message to your friend.", exampleThai:"ส่งข้อความหาเพื่อน", rhymeGroup:"age" },
  { id:345, word:"letter", phonetic:"/ˈletər/", thai:"จดหมาย", category:"communication", level:"A1", rhyme:"จด หมาย เขียน ด้วย ใจ ส่ง ความ รัก ถึง", example:"Write a letter to grandma.", exampleThai:"เขียนจดหมายถึงยาย", rhymeGroup:"er" },
  { id:346, word:"news", phonetic:"/njuːz/", thai:"ข่าว", category:"communication", level:"A1", rhyme:"ข่าว สาร รับ รู้ โลก เปลี่ยน ไป ทุก วัน", example:"Watch the news every day.", exampleThai:"ดูข่าวทุกวัน", rhymeGroup:"oos" },
  { id:347, word:"story", phonetic:"/ˈstɔːri/", thai:"เรื่องราว", category:"communication", level:"A1", rhyme:"เรื่อง ราว ดี มี คติ สอน ใจ เสมอ", example:"Tell me a story.", exampleThai:"เล่าเรื่องให้ฉันฟังหน่อย", rhymeGroup:"y" },
  { id:348, word:"joke", phonetic:"/dʒoʊk/", thai:"เรื่องตลก", category:"communication", level:"A2", rhyme:"ตลก ขำ ขัน หัวเราะ ดัง หาย เครียด", example:"Tell me a funny joke.", exampleThai:"เล่าเรื่องตลกให้ฉันฟังหน่อย", rhymeGroup:"oke" },
  { id:349, word:"speech", phonetic:"/spiːtʃ/", thai:"สุนทรพจน์/การพูด", category:"communication", level:"B1", rhyme:"สุนทร พจน์ พูด จาก ใจ จริง ฟัง แล้ว ประทับ ใจ", example:"Give a speech to the class.", exampleThai:"กล่าวสุนทรพจน์ต่อชั้นเรียน", rhymeGroup:"each" },
  { id:350, word:"conversation", phonetic:"/ˌkɒnvəˈseɪʃn/", thai:"การสนทนา", category:"communication", level:"A1", rhyme:"สนทนา แลก เปลี่ยน ความ คิด ดี งาม", example:"Have a nice conversation.", exampleThai:"สนทนาพูดคุยกันดีๆ", rhymeGroup:"on" },

  // B1 - Money & Shopping
  { id:351, word:"price", phonetic:"/praɪs/", thai:"ราคา", category:"shopping", level:"A1", rhyme:"ราคา พอ ดี คุ้ม ค่า น่า ซื้อ", example:"What's the price of this?", exampleThai:"อันนี้ราคาเท่าไหร่?", rhymeGroup:"ice" },
  { id:352, word:"cheap", phonetic:"/tʃiːp/", thai:"ถูก (ราคา)", category:"shopping", level:"A1", rhyme:"ถูก ดี มี คุณ ภาพ ดี ด้วย", example:"This shop is very cheap.", exampleThai:"ร้านนี้ราคาถูกมาก", rhymeGroup:"eap" },
  { id:353, word:"expensive", phonetic:"/ɪkˈspensɪv/", thai:"แพง", category:"shopping", level:"A1", rhyme:"แพง แต่ คุณ ภาพ ดี คุ้ม ค่า นัก", example:"This bag is too expensive.", exampleThai:"กระเป๋าใบนี้แพงมาก", rhymeGroup:"ive" },
  { id:354, word:"shop", phonetic:"/ʃɒp/", thai:"ร้านค้า/ช้อปปิ้ง", category:"shopping", level:"A1", rhyme:"ร้าน ค้า แวะ ซื้อ ของ ที่ ชอบ ใจ", example:"Let's go to the shop.", exampleThai:"ไปร้านค้ากันเถอะ", rhymeGroup:"op" },
  { id:355, word:"pay", phonetic:"/peɪ/", thai:"จ่ายเงิน", category:"shopping", level:"A1", rhyme:"จ่าย เงิน แล้ว ได้ สิ่ง ที่ อยาก ได้", example:"Pay at the cashier.", exampleThai:"จ่ายเงินที่แคชเชียร์", rhymeGroup:"ay" },
  { id:356, word:"buy", phonetic:"/baɪ/", thai:"ซื้อ", category:"shopping", level:"A1", rhyme:"ซื้อ ของ ดี มี คุณ ภาพ คุ้ม ค่า", example:"Buy a gift for your mom.", exampleThai:"ซื้อของขวัญให้แม่", rhymeGroup:"y" },
  { id:357, word:"sell", phonetic:"/sel/", thai:"ขาย", category:"shopping", level:"A1", rhyme:"ขาย ของ ดี บอก ต่อ คน อื่น ได้ เลย", example:"He sells vegetables at the market.", exampleThai:"เขาขายผักที่ตลาด", rhymeGroup:"ell" },
  { id:358, word:"discount", phonetic:"/ˈdɪskaʊnt/", thai:"ส่วนลด", category:"shopping", level:"A2", rhyme:"ส่วน ลด ดี ซื้อ เพิ่ม ประหยัด เงิน", example:"There's a discount today!", exampleThai:"วันนี้มีส่วนลด!", rhymeGroup:"ount" },

  // B1 - Nature extras
  { id:359, word:"earthquake", phonetic:"/ˈɜːθkweɪk/", thai:"แผ่นดินไหว", category:"nature", level:"B1", rhyme:"แผ่น ดิน ไหว สั่น สะเทือน แต่ เรา สู้ ได้", example:"An earthquake shook the city.", exampleThai:"แผ่นดินไหวสั่นสะเทือนเมือง", rhymeGroup:"ake" },
  { id:360, word:"flood", phonetic:"/flʌd/", thai:"น้ำท่วม", category:"nature", level:"B1", rhyme:"น้ำ ท่วม มา แต่ เรา ช่วย กัน ฝ่า ไป", example:"The flood destroyed many houses.", exampleThai:"น้ำท่วมทำลายบ้านหลายหลัง", rhymeGroup:"ud" },
  { id:361, word:"grass", phonetic:"/ɡrɑːs/", thai:"หญ้า", category:"nature", level:"A1", rhyme:"หญ้า เขียว อ่อน นุ่ม เดิน เท้า เย็น สบาย", example:"The grass is green and soft.", exampleThai:"หญ้าสีเขียวและนุ่ม", rhymeGroup:"ass" },
  { id:362, word:"lake", phonetic:"/leɪk/", thai:"ทะเลสาบ", category:"nature", level:"A1", rhyme:"ทะเล สาบ สงบ เงียบ สวย งาม น่า มอง", example:"The lake is calm and beautiful.", exampleThai:"ทะเลสาบสงบและสวยงาม", rhymeGroup:"ake" },
  { id:363, word:"cave", phonetic:"/keɪv/", thai:"ถ้ำ", category:"nature", level:"A2", rhyme:"ถ้ำ มืด ลึก ลับ ซ่อน สมบัติ ธรรม ชาติ", example:"Bats live in caves.", exampleThai:"ค้างคาวอาศัยอยู่ในถ้ำ", rhymeGroup:"ave" },
  { id:364, word:"waterfall", phonetic:"/ˈwɔːtəfɔːl/", thai:"น้ำตก", category:"nature", level:"A2", rhyme:"น้ำ ตก ไหล ลด หลั่น งาม ตา ดู ไม่ เบื่อ", example:"The waterfall is very beautiful.", exampleThai:"น้ำตกสวยงามมาก", rhymeGroup:"all" },
  { id:365, word:"sand", phonetic:"/sænd/", thai:"ทราย", category:"nature", level:"A1", rhyme:"ทราย ละเอียด อ่อน เดิน เท้า เย็น ชาย ทะเล", example:"Build castles in the sand.", exampleThai:"สร้างปราสาทบนทราย", rhymeGroup:"and" },

  // B1 - Academic/Study skills
  { id:366, word:"research", phonetic:"/rɪˈsɜːtʃ/", thai:"การค้นคว้า", category:"school", level:"B1", rhyme:"ค้น คว้า หา ความ รู้ ไม่ มี วัน หยุด", example:"Research the topic carefully.", exampleThai:"ค้นคว้าหัวข้อนั้นอย่างรอบคอบ", rhymeGroup:"earch" },
  { id:367, word:"project", phonetic:"/ˈprɒdʒekt/", thai:"โครงงาน", category:"school", level:"A2", rhyme:"โครง งาน ทำ ร่วม กัน ดี กว่า คน เดียว", example:"Work on the project together.", exampleThai:"ทำโครงงานร่วมกัน", rhymeGroup:"ect" },
  { id:368, word:"presentation", phonetic:"/ˌprezənˈteɪʃn/", thai:"การนำเสนอ", category:"school", level:"B1", rhyme:"นำ เสนอ ชัด เจน มั่น ใจ ทุก คน ปรบ มือ", example:"Give a great presentation.", exampleThai:"นำเสนองานได้ยอดเยี่ยม", rhymeGroup:"on" },
  { id:369, word:"essay", phonetic:"/ˈeseɪ/", thai:"เรียงความ", category:"school", level:"B1", rhyme:"เรียง ความ เขียน จาก ใจ จริง ดี ที่สุด", example:"Write an essay about nature.", exampleThai:"เขียนเรียงความเกี่ยวกับธรรมชาติ", rhymeGroup:"ay" },
  { id:370, word:"grammar", phonetic:"/ˈɡræmər/", thai:"ไวยากรณ์", category:"school", level:"B1", rhyme:"ไวยา กรณ์ ฝึก มาก ก็ เก่ง ขึ้น เอง", example:"Study grammar every day.", exampleThai:"ฝึกไวยากรณ์ทุกวัน", rhymeGroup:"ar" },

  // B1 - Technology extras  
  { id:371, word:"website", phonetic:"/ˈwebsaɪt/", thai:"เว็บไซต์", category:"technology", level:"A2", rhyme:"เว็บ ไซต์ ค้น หา ข้อมูล ได้ ทุก อย่าง", example:"Visit our website for more info.", exampleThai:"เยี่ยมชมเว็บไซต์ของเราเพื่อข้อมูลเพิ่มเติม", rhymeGroup:"ite" },
  { id:372, word:"software", phonetic:"/ˈsɒftweər/", thai:"ซอฟต์แวร์", category:"technology", level:"B1", rhyme:"ซอฟต์ แวร์ ช่วย ให้ คอม พิว เตอร์ ทำงาน ได้", example:"Update your software regularly.", exampleThai:"อัพเดทซอฟต์แวร์สม่ำเสมอ", rhymeGroup:"are" },
  { id:373, word:"password", phonetic:"/ˈpɑːswɜːd/", thai:"รหัสผ่าน", category:"technology", level:"A2", rhyme:"รหัส ผ่าน ลับ เก็บ ไว้ อย่า บอก ใคร", example:"Use a strong password.", exampleThai:"ใช้รหัสผ่านที่แข็งแกร่ง", rhymeGroup:"ord" },
  { id:374, word:"screen", phonetic:"/skriːn/", thai:"หน้าจอ", category:"technology", level:"A2", rhyme:"หน้า จอ สว่าง แสดง ข้อมูล ชัด เจน", example:"The screen shows the results.", exampleThai:"หน้าจอแสดงผลลัพธ์", rhymeGroup:"een" },
  { id:375, word:"keyboard", phonetic:"/ˈkiːbɔːd/", thai:"แป้นพิมพ์", category:"technology", level:"A2", rhyme:"แป้น พิมพ์ ตัว อักษร ลง หน้า จอ ได้", example:"Type on the keyboard.", exampleThai:"พิมพ์บนแป้นพิมพ์", rhymeGroup:"oard" },

  // B2 - Emotions & Mindset
  { id:376, word:"optimistic", phonetic:"/ˌɒptɪˈmɪstɪk/", thai:"มองโลกในแง่ดี", category:"adjectives", level:"B2", rhyme:"มอง โลก แง่ ดี ชีวิต มี แต่ สุข", example:"Stay optimistic in hard times.", exampleThai:"มองโลกในแง่ดีในช่วงเวลาที่ยาก", rhymeGroup:"ic" },
  { id:377, word:"determined", phonetic:"/dɪˈtɜːmɪnd/", thai:"มุ่งมั่น", category:"adjectives", level:"B1", rhyme:"มุ่ง มั่น ตั้ง ใจ ไม่มี สิ่ง ใด หยุด ได้", example:"Be determined to reach your goals.", exampleThai:"มุ่งมั่นไปสู่เป้าหมาย", rhymeGroup:"ed" },
  { id:378, word:"flexible", phonetic:"/ˈfleksɪbl/", thai:"ยืดหยุ่น", category:"adjectives", level:"B1", rhyme:"ยืด หยุ่น ปรับ ตัว ได้ ทุก สถาน การณ์", example:"Be flexible and adapt.", exampleThai:"จงยืดหยุ่นและปรับตัว", rhymeGroup:"le" },
  { id:379, word:"grateful", phonetic:"/ˈɡreɪtfl/", thai:"รู้สึกขอบคุณ", category:"adjectives", level:"B1", rhyme:"ขอบ คุณ ทุก สิ่ง ที่ มี ใจ สุข ทุก วัน", example:"Be grateful for what you have.", exampleThai:"จงขอบคุณสิ่งที่มีอยู่", rhymeGroup:"ul" },
  { id:380, word:"motivated", phonetic:"/ˈmoʊtɪveɪtɪd/", thai:"มีแรงบันดาลใจ", category:"adjectives", level:"B1", rhyme:"มี แรง บัน ดาล ใจ ทำ ดี ไม่มี หยุด", example:"Stay motivated every day.", exampleThai:"มีแรงบันดาลใจทุกวัน", rhymeGroup:"ed" },

  // B1 - Global topics
  { id:381, word:"technology", phonetic:"/tekˈnɒlədʒi/", thai:"เทคโนโลยี", category:"society", level:"A2", rhyme:"เทค โน โล ยี เปลี่ยน โลก ให้ ดี ขึ้น", example:"Technology changes our lives.", exampleThai:"เทคโนโลยีเปลี่ยนชีวิตเรา", rhymeGroup:"y" },
  { id:382, word:"science", phonetic:"/ˈsaɪəns/", thai:"วิทยาศาสตร์", category:"society", level:"A1", rhyme:"วิทยา ศาสตร์ ค้น พบ สิ่ง ใหม่ ทุก วัน", example:"Science helps us understand the world.", exampleThai:"วิทยาศาสตร์ช่วยให้เราเข้าใจโลก", rhymeGroup:"ence" },
  { id:383, word:"research", phonetic:"/rɪˈsɜːtʃ/", thai:"การวิจัย", category:"society", level:"B1", rhyme:"วิ จัย ค้น หา ความ จริง เพื่อ โลก ที่ ดี", example:"Scientific research saves lives.", exampleThai:"การวิจัยทางวิทยาศาสตร์ช่วยชีวิต", rhymeGroup:"earch" },
  { id:384, word:"global", phonetic:"/ˈɡloʊbl/", thai:"ทั่วโลก", category:"society", level:"B1", rhyme:"ทั่ว โลก เชื่อม ต่อ กัน ด้วย ใจ ที่ ดี", example:"This is a global problem.", exampleThai:"นี่คือปัญหาระดับโลก", rhymeGroup:"al" },
  { id:385, word:"culture", phonetic:"/ˈkʌltʃər/", thai:"วัฒนธรรม", category:"society", level:"A2", rhyme:"วัฒน ธรรม หลาก หลาย สวย งาม ควร เรียน รู้", example:"Respect other cultures.", exampleThai:"เคารพวัฒนธรรมอื่น", rhymeGroup:"er" },

  // A1 - Days & Months
  { id:386, word:"Monday", phonetic:"/ˈmʌndeɪ/", thai:"วันจันทร์", category:"time", level:"A1", rhyme:"จันทร์ เริ่ม สัปดาห์ ใหม่ ตั้ง ใจ ดี", example:"School starts on Monday.", exampleThai:"โรงเรียนเริ่มวันจันทร์", rhymeGroup:"ay" },
  { id:387, word:"Friday", phonetic:"/ˈfraɪdeɪ/", thai:"วันศุกร์", category:"time", level:"A1", rhyme:"ศุกร์ มา แล้ว หัวใจ เต้น ดัง หยุด สัก ที", example:"I love Fridays!", exampleThai:"ฉันชอบวันศุกร์!", rhymeGroup:"ay" },
  { id:388, word:"weekend", phonetic:"/ˈwiːkend/", thai:"วันหยุดสุดสัปดาห์", category:"time", level:"A1", rhyme:"วัน หยุด สุด สัปดาห์ พัก ผ่อน สบาย ใจ", example:"I relax on the weekend.", exampleThai:"ฉันพักผ่อนในวันหยุด", rhymeGroup:"end" },
  { id:389, word:"holiday", phonetic:"/ˈhɒlɪdeɪ/", thai:"วันหยุด", category:"time", level:"A1", rhyme:"วัน หยุด หัวใจ ร่า เริง สนุก สนาน", example:"We travel on holidays.", exampleThai:"เราเดินทางในวันหยุด", rhymeGroup:"ay" },
  { id:390, word:"birthday", phonetic:"/ˈbɜːθdeɪ/", thai:"วันเกิด", category:"time", level:"A1", rhyme:"วัน เกิด มา ขอ ให้ มี ความ สุข นาน", example:"Happy birthday to you!", exampleThai:"สุขสันต์วันเกิด!", rhymeGroup:"ay" },

  // B1 - More complex vocabulary
  { id:391, word:"experience", phonetic:"/ɪkˈspɪəriəns/", thai:"ประสบการณ์", category:"values", level:"B1", rhyme:"ประสบ การณ์ สอน ดี กว่า หนังสือ เล่ม ใด", example:"Experience is the best teacher.", exampleThai:"ประสบการณ์คือครูที่ดีที่สุด", rhymeGroup:"ence" },
  { id:392, word:"decision", phonetic:"/dɪˈsɪʒn/", thai:"การตัดสินใจ", category:"values", level:"B1", rhyme:"ตัด สิน ใจ ดี คิด ดี แล้ว ค่อย ทำ", example:"Make good decisions in life.", exampleThai:"ตัดสินใจดีๆ ในชีวิต", rhymeGroup:"on" },
  { id:393, word:"goal", phonetic:"/ɡoʊl/", thai:"เป้าหมาย", category:"values", level:"B1", rhyme:"เป้า หมาย ชัด เจน ก้าว ไป ถึง แน่ ๆ", example:"Set a goal and work for it.", exampleThai:"ตั้งเป้าหมายและทำงานไปสู่มัน", rhymeGroup:"oal" },
  { id:394, word:"future", phonetic:"/ˈfjuːtʃər/", thai:"อนาคต", category:"values", level:"A1", rhyme:"อนา คต สด ใส ถ้า วัน นี้ ทำ ดี", example:"Think about your future.", exampleThai:"คิดถึงอนาคตของคุณ", rhymeGroup:"er" },
  { id:395, word:"memory", phonetic:"/ˈmeməri/", thai:"ความทรงจำ", category:"values", level:"B1", rhyme:"ความ ทรง จำ ดี เก็บ ไว้ ใน หัวใจ", example:"Keep good memories forever.", exampleThai:"เก็บความทรงจำดีๆ ไว้ตลอดไป", rhymeGroup:"y" },
  { id:396, word:"teamwork", phonetic:"/ˈtiːmwɜːk/", thai:"การทำงานเป็นทีม", category:"values", level:"B1", rhyme:"ทำ งาน ทีม ร่วม ใจ สำเร็จ ไว กว่า", example:"Teamwork makes dreams work.", exampleThai:"การทำงานเป็นทีมทำให้ฝันเป็นจริง", rhymeGroup:"ork" },
  { id:397, word:"leadership", phonetic:"/ˈliːdəʃɪp/", thai:"ความเป็นผู้นำ", category:"values", level:"B1", rhyme:"ผู้ นำ ดี นำ ทีม ไป สู่ ความ สำเร็จ", example:"Good leadership inspires others.", exampleThai:"ผู้นำที่ดีสร้างแรงบันดาลใจ", rhymeGroup:"ip" },
  { id:398, word:"kindness", phonetic:"/ˈkaɪndnəs/", thai:"ความใจดี", category:"values", level:"B1", rhyme:"ใจ ดี ทำ โลก สวย งาม ขึ้น ทุก วัน", example:"Kindness costs nothing.", exampleThai:"ความใจดีไม่มีราคา", rhymeGroup:"ness" },
  { id:399, word:"patience", phonetic:"/ˈpeɪʃns/", thai:"ความอดทน", category:"values", level:"B1", rhyme:"อด ทน รอ ได้ ผล ดี กว่า ใจ ร้อน", example:"Patience is a great virtue.", exampleThai:"ความอดทนเป็นคุณธรรมที่ยิ่งใหญ่", rhymeGroup:"ence" },
  { id:400, word:"happiness", phonetic:"/ˈhæpinəs/", thai:"ความสุข", category:"values", level:"A1", rhyme:"ความ สุข อยู่ ใกล้ แค่ มอง ให้ เห็น", example:"Happiness comes from within.", exampleThai:"ความสุขมาจากภายใน", rhymeGroup:"ness" },
];

const CATEGORIES = [
  { id:"all", name:"ทั้งหมด", emoji:"📚", color:"#6366f1" },
  { id:"animals", name:"สัตว์", emoji:"🐾", color:"#f59e0b" },
  { id:"colors", name:"สี", emoji:"🌈", color:"#ec4899" },
  { id:"food", name:"อาหาร", emoji:"🍎", color:"#10b981" },
  { id:"school", name:"โรงเรียน", emoji:"✏️", color:"#3b82f6" },
  { id:"body", name:"ร่างกาย", emoji:"👤", color:"#ef4444" },
  { id:"nature", name:"ธรรมชาติ", emoji:"🌿", color:"#22c55e" },
  { id:"family", name:"ครอบครัว", emoji:"👨‍👩‍👧", color:"#f97316" },
  { id:"home", name:"บ้าน", emoji:"🏠", color:"#84cc16" },
  { id:"transport", name:"ยานพาหนะ", emoji:"🚗", color:"#06b6d4" },
  { id:"actions", name:"การกระทำ", emoji:"⚡", color:"#a855f7" },
  { id:"feelings", name:"ความรู้สึก", emoji:"💖", color:"#f43f5e" },
  { id:"adjectives", name:"คุณศัพท์", emoji:"✨", color:"#8b5cf6" },
  { id:"time", name:"เวลา", emoji:"⏰", color:"#0ea5e9" },
  { id:"numbers", name:"ตัวเลข", emoji:"🔢", color:"#f59e0b" },
  { id:"places", name:"สถานที่", emoji:"📍", color:"#10b981" },
  { id:"technology", name:"เทคโนโลยี", emoji:"💻", color:"#3b82f6" },
  { id:"clothes", name:"เสื้อผ้า", emoji:"👕", color:"#ec4899" },
  { id:"sports", name:"กีฬา", emoji:"⚽", color:"#f97316" },
  { id:"arts", name:"ศิลปะ", emoji:"🎨", color:"#8b5cf6" },
  { id:"work", name:"การงาน", emoji:"💼", color:"#64748b" },
  { id:"health", name:"สุขภาพ", emoji:"❤️", color:"#ef4444" },
  { id:"environment", name:"สิ่งแวดล้อม", emoji:"🌍", color:"#22c55e" },
  { id:"society", name:"สังคม", emoji:"🤝", color:"#06b6d4" },
  { id:"values", name:"คุณค่า", emoji:"⭐", color:"#a855f7" },
  { id:"travel", name:"การเดินทาง", emoji:"✈️", color:"#0ea5e9" },
  { id:"communication", name:"การสื่อสาร", emoji:"💬", color:"#10b981" },
  { id:"shopping", name:"การช้อปปิ้ง", emoji:"🛍️", color:"#f59e0b" },
  { id:"weather", name:"สภาพอากาศ", emoji:"🌤️", color:"#06b6d4" },
];
